### ISSUE TITLE
v5.20.5 not market as the latest release

### ISSUE THREAD

**Issue by es20490446e** [tildearrow/kwin-lowlatency#109]
In:
https://github.com/tildearrow/kwin-lowlatency/releases

v5.20.5 isn't market as the latest release. Is there a reason for that?

It could be because the release doesn't have a title/description, so GitHub doesn't understand it is a full release.

**Comment by tildearrow** [comment]
Sorry about this! When releasing 5.20.5 I was kind of in a rush and forgot to mark it as a release :<
