### ISSUE TITLE
Just opening this to say that this is still smoother/lower latency for me than 5.21

### ISSUE THREAD

**Issue by pushqrdx** [tildearrow/kwin-lowlatency#111]
Ran both this and 5.21 on lower latency settings for both and i can tell that this has lower latency, i wish you keep working on this, it's awesome

**Comment by PrMinisterGR** [comment]
How did you manage to run this in 5.21? Which distro?

**Comment by pushqrdx** [comment]
> How did you manage to run this in 5.21? Which distro?

I didn't i compared to before upgrade, i wish @tildearrow upgrades this to 5.21

**Comment by tildearrow** [comment]
Closing since KWin-lowlatency 5.22/5.23 is a thing now.
