### ISSUE TITLE
High latency under Intel without horrible hack

### ISSUE THREAD

**Issue by tildearrow** [tildearrow/kwin-lowlatency#13]
glFinish() seems to not wait under Intel, and glXWaitVideoSyncSGI has a chance of freezing...

Related to issue #10

**Comment by tildearrow** [comment]
My bug report in the Mesa bugtracker (https://bugs.freedesktop.org/show_bug.cgi?id=110706#c1) isn't getting fixed, so I can't do much about this...

**Comment by qwertychouskie** [comment]
> My bug report isn't getting

Getting what?

**Comment by tildearrow** [comment]
Sorry, forgot to finish the comment.
