### ISSUE TITLE
Sometimes it doesn't register keyboard shortcuts

### ISSUE THREAD

**Issue by tildearrow** [tildearrow/kwin-lowlatency#14]
Sometimes when starting KWin-lowlatency and pressing Alt-Tab, it literally passes Alt-Tab to the focused application, effectively not allowing me to switch between windows until I restart the compositor.

**Comment by tildearrow** [comment]
[Possibly related issue](https://bugs.kde.org/show_bug.cgi?id=407000)

**Comment by laloch** [comment]
Or maybe [this one](https://bugs.kde.org/show_bug.cgi?id=400658). It is, however, reported against wayland.

**Comment by tildearrow** [comment]
Num Lock was disabled when this occurred.

**Comment by tildearrow** [comment]
Seems like I cannot reproduce this anymore. It must have been fixed upstream at some point.
