### ISSUE TITLE
5.15.90 Transparent titlebars

### ISSUE THREAD

**Issue by Izaic** [tildearrow/kwin-lowlatency#15]
The titlebars are almost fully transparent (there is a outline on the outside where the border usually ends). Compiled it from 2048e9f 5.15.90.

Seems to work otherwise, and it seems to allow me to fully interact with the buttons that are invisible.

Using a RX 560 on Arch Linux and AMDGPU drivers.

**Comment by tildearrow** [comment]
Did you test under official KWin?

**Comment by Izaic** [comment]
Yes, i did both a nested test, and having it the lone compositor. I just recompiled and it started working, i should've noticed the changes weren't applied to the compositor KCM. Sorry.

**Comment by tildearrow** [comment]
That's fine. If you reproduce this problem again, please re-open.
