### ISSUE TITLE
Doesn't compile on Solus

### ISSUE THREAD

**Issue by Vistaus** [tildearrow/kwin-lowlatency#16]
Edit: sorry, my mistake. Compiles fine now :)

**Comment by tildearrow** [comment]
Although I am curious: what CMake command did you use to generate the Makefile? Kinda suspicious that it failed when building my effect.

**Comment by Vistaus** [comment]
> Although I am curious: what CMake command did you use to generate the Makefile? Kinda suspicious that it failed when building my effect.

I used the one from the readme, but the issue was that I was in the wrong folder.
