### ISSUE TITLE
The freeze fix commit causes high CPU load and high latency increase

### ISSUE THREAD

**Issue by realnc** [tildearrow/kwin-lowlatency#17]
Using 5.15.6 causes one CPU core to nearly max out when there's changes on the desktop (like moving a window or playing a video). It also causes a big increase in latency. Reverting commit 73f09f6e11ce806064d0360bef1383e0779d9fa4 fixes the issue.

This is on a GTX 980 Ti using the nvidia 430.14 driver on an AMD64 Gentoo install. Plasma 5.15.5. X.Org server 1.20.5.

**Comment by tildearrow** [comment]
This means NVIDIA doesn't wait for VBlank when glFinish is called... I'll add some NVIDIA-specific code to use the old method.

**Comment by tildearrow** [comment]
I have one question though: are you upgrading to 5.16? I'll push a fix to both versions but I'd prefer to know where to begin first.

**Comment by realnc** [comment]
I'll hold off the 5.16 upgrade in order to test the fix on 5.15 too.

**Comment by tildearrow** [comment]
Please test the latest commit. I've added the old waitSync code back.

**Comment by realnc** [comment]
Just tested and it fixes the issue.

**Comment by tildearrow** [comment]
Good to hear! I will be releasing 5.15.6-2 and 5.16.0-2 with the fix soon.

**Comment by realnc** [comment]
I haven't had the chance to thank you for this project yet. It fixed **all** my issues with video playback in KDE (using MPV as the video player.) No matter what I did previously, I would get some skips/hiccups when watching videos. It was really obnoxious. So I constantly had to disable compositing and switch my monitor to 24Hz or 60Hz or 50Hz, depending on the FPS of the video what I'm watching. It was a constant hassle. With this version of kwin, it's totally fine at 120Hz or 100Hz with compositing enabled, just like under MS Windows.

(I just upgraded to Plasma 5.16 just now, and the Plasma/5.16 branch doesn't compile. But I'll open a new bug about that one.)

**Comment by tildearrow** [comment]
Thank you for the feedback. It is great to know it works well on your system.

(is it due to some EGL header missing? if so, try recreating the build directory. It has occurred to me a few times.)

**Comment by realnc** [comment]
No, it's something else. Building your repo directly works. But generating the patch and applying it to vanilla kwin 5.16 and letting portage apply and build results in:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: effects/CMakeFiles/kwin4_effect_builtins.dir/effect_builtins.cpp.o: in function `KWin::Effect* KWin::BuiltInEffects::createHelper<KWin::MousePosEffect>()':
effect_builtins.cpp:(.text._ZN4KWin14BuiltInEffects12createHelperINS_14MousePosEffectEEEPNS_6EffectEv[_ZN4KWin14BuiltInEffects12createHelperINS_14MousePosEffectEEEPNS_6EffectEv]+0x13): undefined reference to `KWin::MousePosEffect::MousePosEffect()'
collect2: error: ld returned 1 exit status
```

I'm investigating and trying to reproduce when building your sources. Maybe it's a compiler flag or USE lag combination.

**Comment by tildearrow** [comment]
Good morning. Can you please try 5.16.5 to ensure it doesn't bring this bug back?

**Comment by realnc** [comment]
> Good morning. Can you please try 5.16.5 to ensure it doesn't bring this bug back?

No 100% CPU load, but I think there's some lag increase (distance between  cursor and window when moving it around.)

**Comment by tildearrow** [comment]
...are you still using the 430.14 driver?

**Comment by realnc** [comment]
Nope. 435.21.

Could be placebo. I'll need to downgrade kwin again and compare.

**Comment by tildearrow** [comment]
It's been almost 2 months... Hoping that it has been fixed by now.
