### ISSUE TITLE
5.16.0-2 doesn't build

### ISSUE THREAD

**Issue by KAMiKAZOW** [tildearrow/kwin-lowlatency#19]
Full log: https://build.opensuse.org/package/live_build_log/home:KAMiKAZOW:KDE/kwin-lowlatency/openSUSE_Tumbleweed/x86_64

**Comment by realnc** [comment]
fatal error: xcb/xcb_event.h: No such file or directory

Looks like the spec file is missing a dep on xcb-util.

**Comment by KAMiKAZOW** [comment]
Somehow missed the new dependency. Thanks.

**Comment by tildearrow** [comment]
Unrelated question: Is there any way I may be able to contact you to inform you of new releases?

**Comment by KAMiKAZOW** [comment]
I am subscribed to https://github.com/tildearrow/kwin-lowlatency/releases.atom via an RSS reader but my @opensuse.org mail address works as well.
