### ISSUE TITLE
kwin-lowlatency-5.15.6-2.patch includes references to mousepos effect

### ISSUE THREAD

**Issue by agates** [tildearrow/kwin-lowlatency#21]
The `kwin-lowlatency-5.15.6-2.patch` release patchfile includes some leftover references to mousepos while the mousepos effect code itself is not there.

See https://github.com/agates/kwin-lowlatency-overlay/commit/9c2427a20baffc53253484b08d3abaee45429830

**Comment by tildearrow** [comment]
Thanks for reporting. I don't know what caused the removal of the mousepos effect but I'll try to fix it.

**Comment by agates** [comment]
Ahh, so they were left out on accident.  I provided 5.15.6-2 for Gentoo with the references removed, but can update it when these are added.

**Comment by tildearrow** [comment]
Patch updated in website, now with mousepos code.
