### ISSUE TITLE
Recommendations for safely uninstalling?

### ISSUE THREAD

**Issue by Iiari** [tildearrow/kwin-lowlatency#22]
Hello. I see a dramatic improvement with one of my machines with your package (congrats!) but not so much another, and I want to remove it without breaking anything else.  Advice?  Keep all dependencies I presume.  Anything else?  Thank you!

**Comment by tildearrow** [comment]
Did you install using `make install`? If so, then I'd recommend reinstalling stock KWin again.

Can you tell me the non-working machine's specs?

**Comment by Iiari** [comment]
I installed it via the AUR and Pamac.  That's why I'm concerned an uninstall can break things.  Maybe uninstall low latency, and then reinstall kwin immediately thereafter?  

I have a feeling the impact is great on my desktop system with a 120 hz monitor, while my laptop is a 60 hz display and it's just not as obvious.  Here are the stats: 

System:
  Host: MatebookManjKDE 
  Kernel: 4.14.124-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.3.0 
  Desktop: KDE Plasma 5.15.5 tk: Qt 5.12.3 
  info: plank wm: kwin_x11 dm: 
  SDDM Distro: Manjaro Linux 
Machine:
  Type: Laptop System: HUAWEI product: MACH-WX9 v: M14 serial: <filter> 
  Mobo: HUAWEI model: MACH-WX9 v: M14 serial: <filter> UEFI: HUAWEI v: 1.09 
  date: 04/10/2018 
Battery:
  ID-1: BAT0 charge: 28.3 Wh condition: 51.7/56.3 Wh (92%) volts: 7.5/7.6 
  model: DYNAPACK HB4593R1ECW type: Li-ion serial: <filter> 
  status: Discharging cycles: 160 
CPU:
  Topology: Quad Core model: Intel Core i7-8550U bits: 64 type: MT MCP 
  arch: Kaby Lake rev: A L2 cache: 8192 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 31880 
  Speed: 800 MHz min/max: 400/4000 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 800 6: 800 7: 800 8: 801 
Graphics:
  Device-1: Intel UHD Graphics 620 vendor: Huawei driver: i915 v: kernel 
  bus ID: 00:02.0 chip ID: 8086:5917 
  Device-2: NVIDIA GP108M [GeForce MX150] vendor: Huawei driver: nouveau 
  v: kernel bus ID: 01:00.0 chip ID: 10de:1d12 
  Display: x11 server: X.Org 1.20.5 driver: intel,nouveau 
  unloaded: modesetting alternate: fbdev,nv,vesa compositor: kwin_x11 
  resolution: 1920x1280_60.00~60Hz 
  OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2) 
  v: 4.5 Mesa 19.0.6 compat-v: 3.0 direct render: Yes 
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: Huawei 
  driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:9d71 
  Sound Server: ALSA v: k4.14.124-1-MANJARO 
Network:
  Device-1: Intel Wireless 8265 / 8275 vendor: Huawei driver: iwlwifi 
  v: kernel port: 3000 bus ID: 3c:00.0 chip ID: 8086:24fd 
  IF: wlp60s0 state: up mac: <filter> 
  IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:
  Local Storage: total: 476.94 GiB used: 118.51 GiB (24.8%) 
  ID-1: /dev/nvme0n1 vendor: LITE-ON model: CA3-8D512 size: 476.94 GiB 
  speed: 31.6 Gb/s lanes: 4 serial: <filter> rev: C496406 scheme: GPT 
Partition:
  ID-1: / size: 468.16 GiB used: 118.51 GiB (25.3%) fs: ext4 dev: /dev/dm-0 
Sensors:
  System Temperatures: cpu: 38.0 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 267 Uptime: 2h 15m Memory: 15.46 GiB used: 4.32 GiB (27.9%) 
  Init: systemd v: 242 Compilers: gcc: 8.3.0 clang: 8.0.0 Shell: bash 
  v: 5.0.7 running in: tilix inxi: 3.0.34

**Comment by tildearrow** [comment]
If you install stock KWin it should ask you `kwin-lowlatency and kwin are in conflict`. If it doesn't, please tell me and I'll submit a fix.

**Comment by Iiari** [comment]
I might give it a try later depending upon how brave I am...  Have you noticed any difference in battery life with your package?  Thanks!

**Comment by tildearrow** [comment]
So far I haven't since I've stopped using stock KWin on this laptop long ago.

**Comment by Iiari** [comment]
How would I verify if it or stock kwin is running?  How to turn on middle button closure in windows?

**Comment by tildearrow** [comment]
> How would I verify if it or stock kwin is running?

While there is no direct way to do so, you can try adding the following to the Compositing section in kwinrc (~/.config/kwinrc):
```
MaxFPS=30
RefreshRate=30
```
and check if it halves the framerate.

> How to turn on middle button closure in windows?

System Settings > Desktop Effects > Present Windows (config) > Windows > Middle button > "Close window"
If there is no "Close window" option please tell me.

**Comment by Iiari** [comment]
Wow, never would have found that, thank you!  So low latency must be active for that setting to be there and for it to work.  Interestingly, "Present Windows" is no longer an option in my desktop edges config screen.  The new painting cursor options are there, but present windows is gone.  It's still honoring my prior edge set to present windows expose, however...

**Comment by tildearrow** [comment]
> The new painting cursor options are there, but present windows is gone. It's still honoring my prior edge set to present windows expose, however...

That's abnormal. Can you try relogging in?

**Comment by Iiari** [comment]
![edgeconfig](https://user-images.githubusercontent.com/18463603/60117969-422a8380-9749-11e9-9f47-1c88af299714.png)
I'm not sure what you mean by "relogging in."  This change in the settings is consistent across both the laptop and desktop KDE Manjaro installs, and I've rebooted both at least a half dozen times.  Anything else I can provide you?

**Comment by tildearrow** [comment]
Wait, why does it say "Paint cursor - All Desktops"?
This is definitely a bug. Moving to a new issue...
