### ISSUE TITLE
Does this allow desktop effects to work, and will this seamlessly and easily work and install with Manjaro 18 kde?

### ISSUE THREAD

**Issue by StarrKiss** [tildearrow/kwin-lowlatency#23]

**Comment by tildearrow** [comment]
It should.

**Comment by bvobart** [comment]
Can confirm, kwin version 5.17.5. 

The only problem I had was that Pamac (Manjaro's default GUI and CLI package and AUR helper) would complain that it could not remove the original kwin as that would break the kwin dependency of plasma-workspace IIRC. This was easily solved using `sudo pacman -Rdd kwin && pamac build kwin-lowlatency`, which removes (`-R`) kwin without checking dependencies (`-dd`) and then builds `kwin-lowlatency` from the AUR.

**Comment by tildearrow** [comment]
I wonder how does `pamac` not understand the `conflicts=` field?...
