### ISSUE TITLE
Bug in Screen Edges

### ISSUE THREAD

**Issue by tildearrow** [tildearrow/kwin-lowlatency#24]
![edgeconfig](https://user-images.githubusercontent.com/18463603/60117969-422a8380-9749-11e9-9f47-1c88af299714.png)
I'm not sure what you mean by "relogging in."  This change in the settings is consistent across both the laptop and desktop KDE Manjaro installs, and I've rebooted both at least a half dozen times.  Anything else I can provide you?

_Originally posted by @Iiari in https://github.com/tildearrow/kwin-lowlatency/issues/22#issuecomment-505533486_

Why is there a "Paint cursor" in the Screen Edges config?

**Comment by tildearrow** [comment]
Let's hope the lack of a `MousePos` here is the culprit

https://github.com/tildearrow/kwin-lowlatency/blob/85c79219701886faf17c12956b01cf8a19327554/effects/effect_builtins.h#L34-L74

**Comment by tildearrow** [comment]
Indeed, that was it. @Iiari please confirm with v5.16.2-2

**Comment by Iiari** [comment]
Can you update the version on the AUR?  Thanks!

**Comment by tildearrow** [comment]
Sorry, closed by accident.

I thought you'd edit the PKGBUILD? (or does this mean the fix is effective on your side?)

Updated.

**Comment by Iiari** [comment]
So I updated and it looks fixed!  All is well with the edge configuration...  Congrats, and thanks again for this great contribution to the community.
