### ISSUE TITLE
Add upstream commits

### ISSUE THREAD

**Issue by StarrKiss** [tildearrow/kwin-lowlatency#26]
Specifically those that improve desktop effects appearance such as blur. If the latency changes are small, it shouldnt be too hard to implement.

**Comment by tildearrow** [comment]
KWin-lowlatency closely follows upstream stable releases, but not Git master.

**Comment by StarrKiss** [comment]
It is lacking and has worse desktop effects (r:e blur noise) than normal kwin on Manjaro 18.

**Comment by tildearrow** [comment]
I'm getting confused, as the blur improvements commit **is** there (3c2148a5f)...

Are you sure you're on KWin 5.16? Maybe when cloning it may have set the branch to Plasma/5.15...

**Comment by StarrKiss** [comment]
I didnt clone it, I installed the AUR package. for kwin-lowlatency

**Comment by StarrKiss** [comment]
I didnt clone it, I installed the AUR package. for kwin-lowlatency

**Comment by tildearrow** [comment]
Please provide the output of `kwin_x11 --version`? This does not seem right.

**Comment by StarrKiss** [comment]
5.16.2 The reason why I think it is behind is because this:
![image](https://user-images.githubusercontent.com/13007697/60389173-d7e44c80-9a82-11e9-841d-23dd2416c63c.png)
Is what blur looks like on kwin-lowlatency, when noise is set to medium-high. This persists until i disable noise, and it didnt happepn in normal kwin

**Comment by tildearrow** [comment]
I just tested stock KWin and my patchset to see if there's any difference, but I can't see any in my machine.

**Comment by StarrKiss** [comment]
That's odd. This should be flagged as a new issue, odd noise or something.
