### ISSUE TITLE
Cannot enable compositor on Kubuntu

### ISSUE THREAD

**Issue by Odzinic** [tildearrow/kwin-lowlatency#28]
Hi,

I apologize in advance if Kubuntu/Ubuntu is not supported. I recently compiled and installed kwin-lowlatency with all required dependencies installed. There were no issue during installation but I found that I cannot enable the compositor anymore. Every time I turn on the compositor, kwin crashes several times and reverts to running without a compositor.

I am using Kubuntu 19.04, the latest kwin-lowlatency (5.16.2) and nvidia 430 drivers. I used the repo clone step to get the source and compile it.

Attached is my kwin crash backtrade: [kwin_x11-20190628-133015.kcrash.txt](https://github.com/tildearrow/kwin-lowlatency/files/3340255/kwin_x11-20190628-133015.kcrash.txt). 

Thanks

**Comment by tildearrow** [comment]
Perhaps Ubuntu/Kubuntu installs libraries to a different path from most distros, causing the KWin-lowlatency backends to be installed to a wrong directory and thus causing version conflicts when started which causes the crashes?

Try using:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DCMAKE_INSTALL_LIBEXECDIR=lib/x86_64-linux-gnu -DBUILD_TESTING=OFF
```
instead of
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_LIBEXECDIR=lib -DBUILD_TESTING=OFF
```
?

**Comment by tildearrow** [comment]
Wait. Can you please print the output of `ls /usr/lib`?

**Comment by Odzinic** [comment]
> Wait. Can you please print the output of `ls /usr/lib`?

Of course. Attached is the output.
[usrlib_out.txt](https://github.com/tildearrow/kwin-lowlatency/files/3340634/usrlib_out.txt)

**Comment by tildearrow** [comment]
Can you print the output of:
```
cd /usr/lib
find | grep kwin
```
? This is most likely the final step before I can fix README.md for (K)Ubuntu

**Comment by Odzinic** [comment]
> Can you print the output of:
> 
> ```
> cd /usr/lib
> find | grep kwin
> ```
> 
> ? This is most likely the final step before I can fix README.md for (K)Ubuntu

Attached output. 
[grep_output.txt](https://github.com/tildearrow/kwin-lowlatency/files/3342184/grep_output.txt)

**Comment by tildearrow** [comment]
Yup, `cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DCMAKE_INSTALL_LIBEXECDIR=lib/x86_64-linux-gnu -DBUILD_TESTING=OFF` should do. Can you try using that in your build dir, making again and installing? If it works after that, I'm updating the readme.

**Comment by Odzinic** [comment]
That fixed it for me. Thanks so much for you help and this great patch!

**Comment by tildearrow** [comment]
No problem. Reopening because I still need to update the readme.

**Comment by tildearrow** [comment]
Done. Closing.
