### ISSUE TITLE
Add clarification to README

### ISSUE THREAD

**Issue by eszlari** [tildearrow/kwin-lowlatency#3]
It would be nice, if you could add a note to the README on whether you are planning on upstreaming your work at some point.

**Comment by tildearrow** [comment]
Will do.

**Comment by eszlari** [comment]
Thanks.

Maybe you could also expand on the relation to Wayland a bit. In the README you only write:

> the only problem is that this only works under GLX (which means no X with EGL support, OpenGL ES or Wayland support).

Do you think your fixes apply to Wayland as well? Or are they even needed there?

**Comment by tildearrow** [comment]
Done.

> no, it won't. it hasn't been done yet, since there's no way to ensure every retrace will wait for VBlank (especially on Mesa)... and although I could use DRM VBlank waiting there, it won't work on NVIDIA. sorry.
