### ISSUE TITLE
Add support for  _GTK_FRAME_EXTENTS

### ISSUE THREAD

**Issue by ZaWertun** [tildearrow/kwin-lowlatency#30]
Just read article on reddit that someone added support for  _GTK_FRAME_EXTENTS in kwin.
Could you merge this patch in kwin-lowlatency? It will be awesome :)

There is some info:
[reddit: KWin with _GTK_FRAME_EXTENTS support (sick!)](https://www.reddit.com/r/kde/comments/c7i5zr/kwin_with_gtk_frame_extents_support_sick/)
[gihub: KWin/X11 that can do _GTK_FRAME_EXTENTS ](https://github.com/zzag/arch-kwin-gtk-frame-extents)

**Comment by tildearrow** [comment]
> KWin needs customized KWindowSystem, so build and install it first

This will be a problem...

**Comment by tildearrow** [comment]
I'm contacting the developer of that patchset to see if this can be done without patching KWindowSystem...

**Comment by tildearrow** [comment]
OK, so I think I have a strategy:

~1. Bring support for _GTK_FRAME_EXTENTS as long as you have the custom KWindowSystem installed (and if not then the compositor should still run or something)~
~2. Test~
~3. Add static KWindowSystem to this repo (let's hope this won't break other apps that depend on KWindowSystem)~
~4. Test~
~5. Release 5.16.3~
6. ~Eventually try to~ Get rid of the custom KWindowSystem and do _GTK_FRAME_EXTENTS directly in the compo

**Comment by tildearrow** [comment]
This will be harder to do than I expected as I can't get KWindowSystem to static-ize...

**Comment by tildearrow** [comment]
I'm sorry. I am too late.

**Comment by ZaWertun** [comment]
@tildearrow Better late than never :)
Thanks for your job :+1:

**Comment by realnc** [comment]
Seems to work fine for me. Patch applies cleanly and I see CSD Gtk windows drop shadows now.

If you're on Gentoo, using this is easy. Create the `/etc/portage/patches/kde-plasma/kwin/` and `/etc/portage/patches/kde-plasma/kwindowsystem/` directories. Then.copy `kwin/0001-Implement-_GTK_FRAME_EXTENTS.patch` to `/etc/portage/patches/kde-plasma/kwin/` and `kwindowsystem/0001-Implement-_GTK_FRAME_EXTENTS.patch` to `/etc/portage/patches/kde-frameworks/kwindowsystem/`.

Now just install these two packages again with `emerge -1 kwindowsystem kwin` and restart kwin with `kwin_x11 --replace &`.

**Comment by ZaWertun** [comment]
_GTK_FRAME_EXTENTS support will be merged to the kwin.
http://phabricator.kde.org/D24660
