### ISSUE TITLE
Unclear settings.

### ISSUE THREAD

**Issue by StarrKiss** [tildearrow/kwin-lowlatency#32]
The application doesnt make it clear enough what the difference is between responsiveness and low latency. They seem like roughly the same thing. Maybe changing the names to something more understandable would be a good idea? ( I am still confused for one, because in the readme, you dont explain what the responsiveness option does, only latency)

**Comment by tildearrow** [comment]
I don't know what to change it to, though...
By "Responsiveness" I mean as in added latency to eliminate stutter (especially in low-end systems), but "Favor lack of stuttering" sounds unusual.

**Comment by StarrKiss** [comment]
@tildearrow

Two ideas:

Favor stutter elimination

Favor stutter masking

**Comment by qwertychouskie** [comment]
Maybe have "Less stutter" on one end and "Less latency" on the other.

**Comment by tildearrow** [comment]
Finished. v5.16.3-2 coming soon with changes applied. New menu:
- Less stutter
- Balanced
- Lower latency
- Even lower latency

Thanks for pointing out!

**Comment by tildearrow** [comment]
v5.16.3-2 released with fixes.
