### ISSUE TITLE
kwin_x11 crashes

### ISSUE THREAD

**Issue by Vistaus** [tildearrow/kwin-lowlatency#35]
I tried to install kwin_lowlatency on Clear Linux and it compiles and installs fine, but it doesn't work as kwin crashes immediately upon booting and it can't be started manually either. Here's the output of kwin_x11 --replace :

```
vistaus@ThinkClear ~>kwin_x11 --replace
Module 'org.kde.kwin.decoration' does not contain a module identifier directive - it cannot be protected from external registrations.
Application::crashHandler() called with signal 11; recent crashes: 4
KCrash: Application 'kwin_x11' crashing...
KCrash: Attempting to start /usr/lib64/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
Icon theme "Yaru" not found.
```

gdb does show a symbol lookup error for kwin, but there's no backtrace:

```
vistaus@ThinkClear~/Apps/from=git/kwin-lowlatency/build $ QT_PLUGIN_PATH="$PWD/bin" gdb ./bin/kwin_x11
GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-generic-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
--Type <RET> for more, q to quit, c to continue without paging--c
Reading symbols from ./bin/kwin_x11...
(gdb) run --replace
Starting program: /home/vistaus/Apps/from=git/kwin-lowlatency/build/bin/kwin_x11 --replace
source: Error encountered while sourcing file “/home/vistaus/.local/share/omf/init.fish”:
source: No such file or directory
/home/vistaus/Apps/from=git/kwin-lowlatency/build/bin/kwin_x11: symbol lookup error: /home/vistaus/Apps/from=git/kwin-lowlatency/build/bin/libkwin.so.5: undefined symbol: _ZN12ScreenLocker7KSldApp4lockENS_13EstablishLockEi
[Inferior 1 (process 2584) exited with code 0177]
(gdb) backtrace
No stack.
```

Could you help me solve this?

**Comment by tildearrow** [comment]
Can you provide the output of `ls /usr/lib | tail`?

**Comment by Vistaus** [comment]
> Can you provide the output of `ls /usr/lib | tail`?

Sure :)

```
vistaus@ThinkClear ~/A/f/d/build> ls /usr/lib | tail
systemd
sysusers.d
tc
tcl8
tcl8.6
terminfo
tk8.6
tmpfiles.d
udev
X11
vistaus@ThinkClear ~/A/f/d/build> 
```

**Comment by tildearrow** [comment]
There isn't a x86_64-linux-gnu... ...this doesn't seem right.

Can you provide the backtrace of the installed kwin_x11? (you provided the non-installed one)

**Comment by Vistaus** [comment]
> There isn't a x86_64-linux-gnu... ...this doesn't seem right.

FWIW, even without kwin, Plasma is working fine still (currently using metacity as a workaround) so the absence of x86_64-linux-gnu must be some sort of Clear Linux modification then?

> Can you provide the backtrace of the installed kwin_x11? (you provided the non-installed one)

I tried getting a backtrace of the installed kwin_x11 but run --replace (in gdb) froze after 2 minutes, so I couldn't obtain a backtrace, and the output of run --replace didn't reveal anything else then the above error and some spawned thread messages.

**Comment by tildearrow** [comment]
> I tried getting a backtrace of the installed kwin_x11 but run --replace (in gdb) froze after 2 minutes, so I couldn't obtain a backtrace, and the output of run --replace didn't obtain anything else then the above error and some spawned thread messages.

Try doing so from SSH rather than a local terminal. (remember to set your $DISPLAY)

**Comment by Vistaus** [comment]
> > I tried getting a backtrace of the installed kwin_x11 but run --replace (in gdb) froze after 2 minutes, so I couldn't obtain a backtrace, and the output of run --replace didn't obtain anything else then the above error and some spawned thread messages.
> 
> Try doing so from SSH rather than a local terminal. (remember to set your $DISPLAY)

I'm not really familiar with SSH. How do I do that?

**Comment by tildearrow** [comment]
Do:
```
sudo apt-get install openssh-server
sudo systemctl start sshd
```

In another computer do:
```
sudo apt-get install openssh-client
ssh vistaus@<IPAddressOfMachine>
```

and then you'll get a shell in where you can do the backtracing.

(you can retrieve your machine's IP address by doing `ip addr`)

**Comment by Vistaus** [comment]
Thanks :)

I did it, but it still says there's no backtrace :/

```
(gdb) run --replace
Starting program: /usr/bin/kwin_x11 --replace
source: Error encountered while sourcing file '/home/vistaus/.local/share/omf/init.fish':
source: No such file or directory
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
warning: the debug information found in "/usr/lib/debug//usr/lib64/libgcc_s.so.1.debug" does not match "/usr/lib64/libgcc_s.so.1" (CRC mismatch).
 
warning: the debug information found in "/usr/lib/debug//usr/lib64/libGL.so.1.2.0.debug" does not match "/usr/lib64/libGL.so.1" (CRC mismatch).
 
warning: the debug information found in "/usr/lib/debug//usr/lib64/libGL.so.1.2.0.debug" does not match "/usr/lib64/libGL.so.1" (CRC mismatch).
 
/usr/bin/kwin_x11: FATAL ERROR while trying to open display
[Inferior 1 (process 14472) exited with code 01]
(gdb) backtrace
No stack.
(gdb)
```

**Comment by tildearrow** [comment]
You haven't set the $DISPLAY. Try:
```
DISPLAY=:0 gdb kwin_x11
```

**Comment by Vistaus** [comment]
Oops, you're right! It worked now. Here's the backtrace: https://pastebin.com/RRe1SxDj

**Comment by tildearrow** [comment]
Theme...

Can you try disabling the Yaru theme (both GTK and Qt) and see if that helps?
If it does, I'm going to check what is going on when the theme is used.

**Comment by Vistaus** [comment]
I don't use the Yaru theme (I don't think Clear Linux even has that theme). I use Kvantum for Qt theming. Kvantum worked fine with kwin_lowlatency on Solus, so that can't be the issue.

**Comment by tildearrow** [comment]
Then I wonder why has your first backtrace mentioned Yaru...

Can you provide the output of `./bin/kwin_x11 --replace`? (from the build directory)

**Comment by Vistaus** [comment]
I think it mentions Yaru because I use the Suru icon theme. Given that it's modeled after the Ubuntu Touch icons, it probably wants Yaru as a fallback theme, but it works fine without.

Here's the output:

```
vistaus@ThinkClear ~/A/f/k/build> ./bin/kwin_x11 --replace
./bin/kwin_x11: symbol lookup error: /home/vistaus/Apps/from=git/kwin-lowlatency/build/bin/libkwin.so.5: undefined symbol: _ZN12ScreenLocker7KSldApp4lockENS_13EstablishLockEi
vistaus@ThinkClear ~/A/f/k/build> 
```

**Comment by tildearrow** [comment]
Try deleting your build directory and compiling again.
Then run using `QT_PLUGIN_PATH="$PWD/bin" ./bin/kwin_x11 --replace`.

**Comment by Vistaus** [comment]
Deleted the build directory and recompiled, but still:

> vistaus@ThinkClear~/Apps/from=git/kwin-lowlatency/build $ QT_PLUGIN_PATH="$PWD/bin" ./bin/kwin_x11 --replace
> ./bin/kwin_x11: symbol lookup error: /home/vistaus/Apps/from=git/kwin-lowlatency/build/bin/libkwin.so.5: undefined symbol: _ZN12ScreenLocker7KSldApp4lockENS_13EstablishLockEi
> vistaus@ThinkClear~/Apps/from=git/kwin-lowlatency/build $ 

Should I try compiling using the Ubuntu instructions to see if that makes it work? I know Clear isn't based on Ubuntu, but maybe it uses the same dir structure.

**Comment by tildearrow** [comment]
I doubt the Ubuntu instructions will help, as it only changes the library directories (which don't exist in Clear)...

What is the output of `plasmashell --version`?

**Comment by Vistaus** [comment]
```
vistaus@ThinkClear ~> plasmashell --version
plasmashell 5.16.4
vistaus@ThinkClear ~> 
```

But I'm going to have to postpone getting this to work as the Clear Linux devs broke the Plasma session once again. So I need to wait until it's fixed before I can try getting kwin-lowlatency up and running again. Thanks for all of your help so far, though! :-)

**Comment by Vistaus** [comment]
I'm going to stop using Clear Linux. It's been a fun week, but it's clear to me (no pun intended) that they don't give a hoot about KDE Plasma and its related libraries. So I'll close this for no and move on to some other distro (not going back to Solus) where kwin-lowlatency works fine. Again: thanks for all of your help, you're amazing! :smile_cat:

**Comment by tildearrow** [comment]
Wait, does this mean even stock KWin isn't working on Clear Linux?
