### ISSUE TITLE
kwin-lowlatency and nvidia 435.17 - performance regression?

### ISSUE THREAD

**Issue by torvic9** [tildearrow/kwin-lowlatency#36]
It seems that kwin-lowlatency doesn't work well together with the latest nvidia driver.
Performance (scrolling, moving windows, hovering menus, etc.) is noticeably worse than before with driver 430.40.
Going back to either default kwin or to the previous driver solves this.
What I haven't tried yet is to recompile kwin-lowlatency, although I'm not sure whether and how that would change anything.

(Manjaro, kwin 5.16.4, kernel 4.19, GTX 1070)

**Comment by tildearrow** [comment]
Sorry, I was sick yesterday and could not attend your bug report in time.

Please comment out all instances of "glFinish();", and try again. I want to see if it has to do with that call.

**Comment by torvic9** [comment]
No problem, I hope your health is fine again.

Please note that I'm not a coder and I don't speak C++.
I grepped for the glFinish string and found 3 instances of it, which I then commented out, created a patchfile, inserted it into the PKGBUILD, and recompiled.

Not 100% sure, but I don't think it made a difference.

Here's the patchfile so that you can check whether I did this correctly:
https://gist.github.com/torvic9/f4e486af6010133b205c3d0c6a17c3d6

**Comment by tildearrow** [comment]
Can you try commenting the "waitSync" part in plugins/platforms/x11/standalone/glxbackend.cpp at line 765?

**Comment by torvic9** [comment]
On top of the previous "glFinish" changes?
Wouldn't that mean to change the entire "if" clause?

**Comment by tildearrow** [comment]
No, separate.

**Comment by tildearrow** [comment]
Also, can you try with 435.21?

**Comment by tildearrow** [comment]
I must hurry! Daniel in the other side, already fixed this issue in GNOME (and he even gets a chance in mainline).

So please give me 2 hours to sleep, 1 to eat, 1 to go to bathroom, 1 to eat, 1 to dress/get ready, 2 for an event I must attend, 1 for going back home, 0.5 to eat, 0.5 to plug in the NVIDIA card back (yeah removed it because it was causing my AMD card to shut off) and finally get this fixed before tomorrow otherwise 5.16.5 will be a crappy release and nobody will want it.

So at 8-9pm I will be ready to begin looking at this and probably add a "VSync control" option in case you're in a working version

**Comment by tildearrow** [comment]
Please try with latest git version. I have pushed a fix.

**Comment by torvic9** [comment]
Sorry for not responding earlier, didn't have time...
I'm now on 435.21 as well and will report back later today.

EDIT: yes, I think you did it :-) 
Performance is now good again, as it seems, even slightly better than default kwin.
You can close this issue I guess.

**Comment by tildearrow** [comment]
Great. Thanks for the feedback!

**Comment by realnc** [comment]
I noticed 5.18.2 enabled this hack. I'm on 5.18.1 right now with nvidia driver 440.59, vsync mechanism set to automatic and I'm not seeing any issues. To get the current behavior after the upgrade, I assume I need to choose the "none and hope for the best" setting?

**Comment by tildearrow** [comment]
@realnc Yep, exactly.
See issue #42 as well
