### ISSUE TITLE
Difference between Sine, Linear and Quadratic animations?

### ISSUE THREAD

**Issue by Vistaus** [tildearrow/kwin-lowlatency#37]
What's the difference between these animation types?

**Comment by tildearrow** [comment]
The difference is that Quadratic/Sine look much smoother than the stock Linear animation curve. You can prove this by maximizing/restoring windows.

**Comment by Vistaus** [comment]
But what exactly does Quadratic do different than Sine?

**Comment by tildearrow** [comment]
The difference is that Sine feels slightly less stiff than Quadratic on higher animation speeds.

This is the curve for Sine:

![sine](https://doc.qt.io/qt-5/images/qeasingcurve-inoutsine.png)

This is the curve for Quadratic:

![quad](https://doc.qt.io/qt-5/images/qeasingcurve-inoutquad.png)

**Comment by Vistaus** [comment]
Thanks :)
