### ISSUE TITLE
half vsync with nvidia 435.21 and opengl compositing

### ISSUE THREAD

**Issue by soulnull** [tildearrow/kwin-lowlatency#39]
Hello,
I just upgraded to 435.21 earlier tonight (on archlinux) and am having worse performance than with nvidia 435.17 (re: https://github.com/tildearrow/kwin-lowlatency/issues/36 ). kwin-lowlatency seems to only be running at half vsync (refresh rate at 60 appeared to be 30fps, 30hz appeared to be 15fps, etc) This included scrolling in various windows, moving windows, etc. Xrender compositing was unaffected. Installing regular kwin restored normal opengl compositing functionality. Willing to help test possible solutions or scenarios.

**Comment by tildearrow** [comment]
Please try with latest git version. I have pushed a fix.

**Comment by soulnull** [comment]
New sources built, and happy to say it's running very smooth now. Thank you.
