### ISSUE TITLE
Add patch files

### ISSUE THREAD

**Issue by agates** [tildearrow/kwin-lowlatency#4]
It would be useful to have a list of patch files used to create kwin-lowlatency to on top of kwin.

**Comment by tildearrow** [comment]
Thank you for the suggestion. This was actually the original planned distribution method, but I changed that idea on the last minute and decided to publish the whole repository instead.

**Comment by agates** [comment]
I mention it because I'd like to include the patches in a gentoo ebuild to include kwin-lowlatency as my main kwin package.

**Comment by tildearrow** [comment]
I see. Isn't it possible to use `git clone` followed by `git checkout` in the ebuild instead? (I still plan to distribute this program in patch format, however)

**Comment by agates** [comment]
At first inspection it didn't seem straightforward to me, but I'll take a closer look.

KDE ebuilds source a kde5.eclass which automatically configure some of the repository cloning logic behind the scenes, based on the version number -- I didn't look into it until now.  Looks like I can probably override that behavior.  Will see if I can provide a new ebuild.

**Comment by tildearrow** [comment]
I'm still waiting for KWin 5.15.5 to get released before I can begin distributing this project in patch format since I have prepared a number of changes since the release of 5.15.4, including [the NVIDIA fix](https://github.com/tildearrow/kwin-lowlatency/issues/2), latency control options, [close option in Present Windows](https://github.com/tildearrow/kwin-lowlatency/issues/5), and possibly even [unredirect](https://github.com/tildearrow/kwin-lowlatency/issues/1) which I haven't put in the AUR since I don't want to break upstream's versioning (I could use pkgrel but NVIDIA fixing is a major change which begs a version bump); and I don't want to pack 5.15.4 as a patch already since it doesn't have the NVIDIA fixes.

**Comment by agates** [comment]
The patch files will allow putting the lowlatency patch set behind a USE flag.  I'm just speculating, but we might be able to push to adding that to the official Gentoo package ebuild, if only disabled by default.

In the mean time, here is an ebuild for `kwin-5.15.49.9999.ebuild` which clones this repository directly.  I recommend using it with the kde overlay.  I had to mask all kde-plasma and kde-frameworks -9999 packages in order to get the build working, but I'm running it right now.

[kwin-5.15.49.9999.ebuild](https://github.com/agates/kwin-lowlatency-gentoo/blob/master/kwin-5.15.49.9999.ebuild)

**Comment by tildearrow** [comment]
I have released kwin-lowlatency 5.15.5 now. May you please test the following patchset?
http://tildearrow.zapto.org/storage/kwin-lowlatency/kwin-lowlatency-5.15.5.patch

**Comment by agates** [comment]
I have it building on Gentoo behind a USE flag.  My work is here.  Still need to test it though.

https://github.com/agates/kwin-lowlatency-gentoo

In the patch file, I removed the change to CMakeLists.txt which was causing a problem during patching, though not sure why.  It seems to build fine without it.

The patch also included a reference to create itself, like patchception, which I removed.

**Comment by agates** [comment]
This is running for me, however window title bars are not appearing -- though I can interact with them, so they at least exist in some manner.  Might this be a result of one of my changes?

**Comment by tildearrow** [comment]
I have updated patch.sh to disable modification of CMakeLists.txt and prevent patch-ception. Please test again and tell me if it works (notes: 1. you may want to remove *.patch before running patch.sh. 2. the patch is now generated outside the repo directory (to prevent patch-ception).).

Also, did you test without using an ebuild? (building from inside the repository, e.g. `mkdir build; cd build; cmake ..; make; QT_PLUGIN_PATH="$PWD/bin" ./bin/kwin_x11 --replace`)
If so, and if it still reproduces, may you tell me your system's specs? (CPU, GPU, driver (`glxinfo | grep OpenGL`) and DDX driver (e.g. amdgpu, modesetting, etc.))

**Comment by agates** [comment]
Looks like it's an issue with my ebuild install, however I don't think it's patch related.  Going to test different compiler settings I have with gentoo LTO first.

Thanks for getting this out!
