### ISSUE TITLE
5.16.5 tag is missing the "v" prefix

### ISSUE THREAD

**Issue by DragoonAethis** [tildearrow/kwin-lowlatency#40]
Just a minor nitpick: The latest 5.16.5 tag is missing the "v" prefix ("v5.16.5"), so a few automatic builders may fail due to this. You might want to replace the current "5.16.5" with "v5.16.5", add a new "v5.16.5" tag or just ignore this and let maintainers handle it on their end. (Eg. this breaks the AUR package right now.)

**Comment by tildearrow** [comment]
Thanks. Fixed.
