### ISSUE TITLE
Kwin crashing when exiting World of Warcraft Classic 

### ISSUE THREAD

**Issue by Odzinic** [tildearrow/kwin-lowlatency#45]
I've been having consistent crashes due to a seg fault when exiting World of Warcraft Classic while it is in fullscreen. I mistakenly sent a bug report to KDE bugtracking before remembering that I'm using kwin-lowlatency. The [bug report](https://bugs.kde.org/show_bug.cgi?id=412049) contains a backtrace and system info. I'm not sure if this is specific to only World of Warcraft Classic but it has been occurring consistently while playing it through multiple Wine versions.

Let me know if I can provide some more information.

**Comment by tildearrow** [comment]
No, sorry. I cannot work on this right now.
I am busy with so many things that I simply cannot keep up.

In the meanwhile, run kwin_x11 under gdb over SSH (there is another bug report that has instructions on how to do that) and when it reaches SIGSEGV do `backtrace` and post here.

In the meanwhile the compositor will keep crashing until I have time to look at it.

Here is the bug report that has backtrace instructions: https://github.com/tildearrow/kwin-lowlatency/issues/35

**Comment by tildearrow** [comment]
OK, so I have added a line of code to check whether the backtrace is right.
Can you please run KWin again, make it crash, and then check whether you see `EMERGENCY: ...? how did we reach here?` in the console?

**Comment by tildearrow** [comment]
What?

Does it not crash anymore?

**Comment by Odzinic** [comment]
@tildearrow Apologies if that was not the right way of dealing with the issue. I stopped playing the game shortly after making this issue and no longer pay subscription so I can't test it out. Felt bad keeping it as an open issue that I can't test and no one else has commented on.
