### ISSUE TITLE
Add these extra instructions to compilation guide

### ISSUE THREAD

**Issue by biblicabeebli** [tildearrow/kwin-lowlatency#48]
(I'm not a C++ dev or KDE expert, just a dev trying to make their gorram laptop work more betterer.  There was a lot of stumbling here.  Recommend you add these directions, it will make this much easier for that expert-non-c++-dev userbase.  Yes, its basic.)

1)
Tell people to run
```kwin --version```
in order to determine the version of kwin installed on their system.  and then some of the branches to check out onto / links for a couple different common versions of kwin-lowlatency for those wget endpoints.

(Assumption: kwin version should match the various KDE framework versions that are available for them on their distro, right?  I mean that its a decent proxy, and if someone is compiling for a different target/version/whatever or somehow have a non-normal kwin version present then they obviously wont need this help.)

2)
Provide a link to the dependency lists installation page for KDE.  I understand that it is most desirable to send peeps to the hacking.md file (which has a link that eventually gets you here) but as there is no .deb for K/Ubuntu at this time, and as such compilation is required for us, it would be nice to have such a link up front.
https://community.kde.org/Guidelines_and_HOWTOs/Build_from_source/Install_the_dependencies

**Comment by tildearrow** [comment]
Done for 5.17.0
