### ISSUE TITLE
Failed build from Aur on Manjaro

### ISSUE THREAD

**Issue by StarrKiss** [tildearrow/kwin-lowlatency#50]
No extensive error, just the quiet death as I call it:
```
home/gstarr/.cache/yay/kwin-lowlatency/src/kwin-lowlatency/screenlockerwatcher.cpp: In member function ‘void KWin::ScreenLockerWatcher::serviceOwnerChanged(const QString&, const QString&, const QString&)’:
/home/gstarr/.cache/yay/kwin-lowlatency/src/kwin-lowlatency/screenlockerwatcher.cpp:84:62: error: ‘AboutToLock’ is not a member of ‘OrgKdeScreensaverInterface’
   84 |         connect(m_kdeInterface, &OrgKdeScreensaverInterface::AboutToLock, this, &ScreenLockerWatcher::aboutToLock);
      |                                                              ^~~~~~~~~~~
make[2]: *** [CMakeFiles/kwin.dir/build.make:1109: CMakeFiles/kwin.dir/screenlockerwatcher.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2147: CMakeFiles/kwin.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: kwin-lowlatency
```

No warning, everytjing going fine, and then it just fails suddenly.

**Comment by tildearrow** [comment]
I hit the same error when testing KWin 5.16.90 with 5.16.5.
Apparently Plasma 5.17 brings a few functions not found in 5.16. Can you try upgrading Plasma first (yes, this includes uninstalling KWin-lowlatency and installing normal KWin) and building again?

**Comment by StarrKiss** [comment]
@tildearrow how would I do this? I tried yay - S plasma-desktop and all it did was reinstall 5.16

**Comment by tildearrow** [comment]
Really? Plasma 5.17 is needed for kwin-lowlatency 5.17.0...
According to a user, they still don't have it in the Manjaro repos.

**Comment by StarrKiss** [comment]
@tildearrow Apparently not. Guess I will hold back on upgrading for now. :( sometimes I chuckle at how much effort I am willing to go through to get an update when some family members are still on win 7 and Android 6

**Comment by StarrKiss** [comment]
@tildearrow  Hello, do you know what AUR package I would install to get the most up-to-date 5.16 vriant of kwin-lowlatency until plasma 5.17 is released on manjaro repos?

**Comment by tildearrow** [comment]
@StarrKiss kwin-lowlatency, commit `f80e2c2f06f3ebd847f2ad7950771b5253cae6b3`

**Comment by StarrKiss** [comment]
@tildearrow  Sorry to bother you again, but when I tried to git checkout f80e2c2f06f3ebd847f2ad7950771b5253cae6b3 it said it reference wasnt a tree?

**Comment by tildearrow** [comment]
Did you checkout in the AUR package's repo? You may have checked out in this repo instead of in the AUR package.

**Comment by tildearrow** [comment]
Added Manjaro-specific notes to README.md.
I hope I can close this issue now.
