### ISSUE TITLE
Build failed on Arch

### ISSUE THREAD

**Issue by Kajanos** [tildearrow/kwin-lowlatency#51]
`[ 92%] Building CXX object plugins/platforms/virtual/CMakeFiles/KWinWaylandVirtualBackend.dir/logging.cpp.o
[ 92%] Linking CXX shared module ../../../bin/org.kde.kwin.waylandbackends/KWinWaylandWaylandBackend.so
[ 92%] Built target KWinWaylandWaylandBackend
[ 92%] Linking CXX shared module ../../../bin/org.kde.kwin.waylandbackends/KWinWaylandVirtualBackend.so
[ 92%] Built target KWinWaylandVirtualBackend
[ 92%] Linking CXX shared module ../../../bin/org.kde.kwin.waylandbackends/KWinWaylandDrmBackend.so
[ 92%] Built target KWinWaylandDrmBackend
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: kwin-lowlatency
`

**Comment by tildearrow** [comment]
Please provide more details. I cannot see the problem.

**Comment by Kajanos** [comment]
Could you please provide where I can find build.log ?
yay -S kwin-lowlatency

**Comment by tildearrow** [comment]
Sorry bug I am not sure since I have never used `yay`. However, is your build multi-threaded? If so, it is possible that the error can be seen before.

(also, quoting my comment in related issue #49, what happens if you try building the package without a helper (and/or after cleaning the build cache)?)

**Comment by Kajanos** [comment]
`/usr/include/qt/QtCore/qvariant.h:134:21: note:   candidate expects 0 arguments, 3 provided
/usr/include/qt/QtCore/qvariant.h:134:21: note: candidate: ‘constexpr QVariant::QVariant(const QVariant&)’
/usr/include/qt/QtCore/qvariant.h:134:21: note:   candidate expects 1 argument, 3 provided
/usr/include/qt/QtCore/qvariant.h:134:21: note: candidate: ‘constexpr QVariant::QVariant(QVariant&&)’
/usr/include/qt/QtCore/qvariant.h:134:21: note:   candidate expects 1 argument, 3 provided
/usr/include/qt/QtCore/qvariant.h: In function ‘T qvariant_cast(const QVariant&) [with T = QVariant]’:
/usr/include/qt/QtCore/qvariant.h:870:11: error: ‘const class QVariant’ has no member named ‘userType’
  870 |     if (v.userType() == QMetaType::QVariant)
      |           ^~~~~~~~
/usr/include/qt/QtCore/qvariant.h:870:36: error: ‘QVariant’ is not a member of ‘QMetaType’
  870 |     if (v.userType() == QMetaType::QVariant)
      |                                    ^~~~~~~~
/usr/include/qt/QtCore/qvariant.h:871:54: error: ‘const class QVariant’ has no member named ‘constData’
  871 |         return *reinterpret_cast<const QVariant *>(v.constData());
      |                                                      ^~~~~~~~~
/usr/include/qt/QtCore/qvariant.h: In function ‘bool qVariantCanConvert(const QVariant&)’:
/usr/include/qt/QtCore/qvariant.h:882:27: error: ‘const class QVariant’ has no member named ‘canConvert’
  882 | { return variant.template canConvert<T>(); }
      |                           ^~~~~~~~~~
/usr/include/qt/QtCore/qvariant.h:882:39: error: expected primary-expression before ‘>’ token
  882 | { return variant.template canConvert<T>(); }
      |                                       ^
/usr/include/qt/QtCore/qvariant.h:882:41: error: expected primary-expression before ‘)’ token
  882 | { return variant.template canConvert<T>(); }
      |                                         ^
In file included from /usr/include/EGL/eglplatform.h:122,
                 from /usr/include/epoxy/egl_generated.h:11,
                 from /usr/include/epoxy/egl.h:46,
                 from /home/sparc/kwin-lowlatency/plugins/qpa/eglhelpers.h:24,
                 from /home/sparc/kwin-lowlatency/plugins/qpa/eglhelpers.cpp:22:
/usr/include/qt/QtCore/qtextstream.h: At global scope:
/usr/include/qt/QtCore/qtextstream.h:78:10: error: expected identifier before ‘int’
   78 |     enum Status {
      |          ^~~~~~
In file included from /usr/include/qt/QtCore/qdebug.h:49,
                 from /usr/include/qt/QtCore/qloggingcategory.h:44,
                 from /usr/include/qt/QtCore/QLoggingCategory:1,
                 from /home/sparc/kwin-lowlatency/plugins/qpa/logging.h:6,
                 from /home/sparc/kwin-lowlatency/plugins/qpa/eglhelpers.cpp:24:
/usr/include/qt/QtCore/qtextstream.h:78:17: error: expected unqualified-id before ‘{’ token
   78 |     enum Status {
      |                 ^
In file included from /usr/include/qt/QtCore/qobject.h:54,
                 from /usr/include/qt/QtCore/qiodevice.h:45,
                 from /usr/include/qt/QtCore/qtextstream.h:43,
                 from /usr/include/qt/QtCore/qdebug.h:49,
                 from /usr/include/qt/QtCore/qloggingcategory.h:44,
                 from /usr/include/qt/QtCore/QLoggingCategory:1,
                 from /home/sparc/kwin-lowlatency/plugins/qpa/logging.h:6,
                 from /home/sparc/kwin-lowlatency/plugins/qpa/eglhelpers.cpp:24:
/usr/include/qt/QtCore/qmetatype.h:554:18: warning: ‘void* create(int, const void*)’ used but never defined
  554 |     static void *create(int type, const void *copy = nullptr);
      |                  ^~~~~~
make[2]: *** [plugins/qpa/CMakeFiles/KWinQpaPlugin.dir/build.make:102: plugins/qpa/CMakeFiles/KWinQpaPlugin.dir/eglhelpers.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8600: plugins/qpa/CMakeFiles/KWinQpaPlugin.dir/all] Error 2`

**Comment by Mjasnik** [comment]
This workaround(?) helped me to solve this issue, just patch before the build. Worksforme :)
Please rename to patch as github won't allow to upload patch files, go figure :)
[kwin-lowlatency-compile-fix.patch.txt](https://github.com/tildearrow/kwin-lowlatency/files/3769115/kwin-lowlatency-compile-fix.patch.txt)

**Comment by torvic9** [comment]
You probably have to pull the latest kwin commits:
https://cgit.kde.org/kwin.git/commit/?id=8e176c8b0d97e78e8b33fac3b5acded277bbcf4f

Edit: success!

**Comment by tildearrow** [comment]
@torvic9 Done!

@Mjasnik ~~@Kajanos~~ ~~@moeryomenko~~ ~~@nazarianin~~ @undu Can you try modifying the PKGBUILD to replace `git checkout v5.17.1` with `git checkout bf1b5789`?
If it finally works, I will release v5.17.1-2 shortly.

**Comment by Kajanos** [comment]
For me looks fine.
[build.log](https://github.com/tildearrow/kwin-lowlatency/files/3773706/build.log)

**Comment by moeryomenko** [comment]
For me looks fine.

**Comment by nazarianin** [comment]
For me looks fine.

**Comment by tildearrow** [comment]
v5.17.1-2 released with the fix.
