### ISSUE TITLE
QT_AUTO_SCREEN_SCALE_FACTOR has been deprecated in >=Qt Gui 5.14

### ISSUE THREAD

**Issue by jiblime** [tildearrow/kwin-lowlatency#52]
https://github.com/tildearrow/kwin-lowlatency/blob/Plasma/5.17/wayStart#L97

https://wiki.qt.io/New_Features_in_Qt_5.14
` Added the QT_ENABLE_HIGHDPI_SCALING environment variable which enables high-dpi scaling based on display DPI. Replaces QT_AUTO_SCREEN_SCALE_FACTOR (now deprecated), and corresponds to the Qt::AA_EnableHighDpiScaling application attribute.`

System information:
```
Gentoo multilib systemd
GCC 9.2.0
cmake 3.14.7
Qt 5.14.0_beta2
Plasma 5.17.1
Frameworks 5.63.0
Apps 19.08.2
```

Possibly related, vlc is now unable to start:
```
$ vlc
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[000000000143f5b0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
WARNING: QApplication was not created in the main() thread.
Warning: QT_AUTO_SCREEN_SCALE_FACTOR is deprecated. Instead use:
   QT_ENABLE_HIGHDPI_SCALING to enable platform plugin controlled per-screen factors.
ASSERT failure in QXcbIntegration: "Initializing accessibility without event-dispatcher!", file qxcbintegration.cpp, line 413
Aborted (core dumped)
```

**Comment by tildearrow** [comment]
What?! The variable I relied upon for proper HiDPI support will be deprecated?

The wayStart script has not been updated because Plasma 5.17 replaces the `startkde` script with a binary `startplasma-x11`.

**Comment by tildearrow** [comment]
Not fixing as I removed the wayStart script (because they turned startplasma into a binary, and that would mean pulling in another repository for it).
