### ISSUE TITLE
Can't install kwin-lowlatency on Kubuntu 19.10

### ISSUE THREAD

**Issue by Alexdegol** [tildearrow/kwin-lowlatency#53]
I am unable to install kwin-lowlatency on Kubuntu 19.10. I followed these steps:

$ wget https://download.kde.org/stable/plasma/5.17.0/kwin-5.17.0.tar.xz
$ wget http://tildearrow.zapto.org/storage/kwin-lowlatency/kwin-lowlatency-5.17.0.patch
EXTRACT
$ tar -xvf kwin-5.17.0.tar.xz
PATCH:
$ cd kwin-5.17.0
$ patch -p1 < ../kwin-lowlatency-5.17.0.patch

BUILDING
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DCMAKE_INSTALL_LIBEXECDIR=lib/x86_64-linux-gnu -DBUILD_TESTING=OFF
$ make

When I run "cmake -DCMAKE [etc.]" the terminal prompts this message:

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Quick" with any
  of the following names:

    Qt5QuickConfig.cmake
    qt5quick-config.cmake

  Add the installation prefix of "Qt5Quick" to CMAKE_PREFIX_PATH or set
  "Qt5Quick_DIR" to a directory containing one of the above files.  If
  "Qt5Quick" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:21 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/alex/kwin-5.17.0/CMakeFiles/CMakeOutput.log".
See also "/home/alex/kwin-5.17.0/CMakeFiles/CMakeError.log".

**Comment by Alexdegol** [comment]
Now I get this:

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


Installing in /alex. Run /home/alex/kwin-5.17.0/prefix.sh to set the environment for KWIN.
-- Could NOT find KF5Config (missing: KF5Config_DIR)
-- Could NOT find KF5Config: found neither KF5ConfigConfig.cmake nor kf5config-config.cmake 
-- Could NOT find KF5ConfigWidgets (missing: KF5ConfigWidgets_DIR)
-- Could NOT find KF5ConfigWidgets: found neither KF5ConfigWidgetsConfig.cmake nor kf5configwidgets-config.cmake 
-- Could NOT find KF5CoreAddons (missing: KF5CoreAddons_DIR)
-- Could NOT find KF5CoreAddons: found neither KF5CoreAddonsConfig.cmake nor kf5coreaddons-config.cmake 
-- Could NOT find KF5Crash (missing: KF5Crash_DIR)
-- Could NOT find KF5Crash: found neither KF5CrashConfig.cmake nor kf5crash-config.cmake 
-- Could NOT find KF5GlobalAccel (missing: KF5GlobalAccel_DIR)
-- Could NOT find KF5GlobalAccel: found neither KF5GlobalAccelConfig.cmake nor kf5globalaccel-config.cmake 
-- Could NOT find KF5I18n (missing: KF5I18n_DIR)
-- Could NOT find KF5I18n: found neither KF5I18nConfig.cmake nor kf5i18n-config.cmake 
-- Could NOT find KF5IconThemes (missing: KF5IconThemes_DIR)
-- Could NOT find KF5IconThemes: found neither KF5IconThemesConfig.cmake nor kf5iconthemes-config.cmake 
-- Could NOT find KF5IdleTime (missing: KF5IdleTime_DIR)
-- Could NOT find KF5IdleTime: found neither KF5IdleTimeConfig.cmake nor kf5idletime-config.cmake 
-- Could NOT find KF5Init (missing: KF5Init_DIR)
-- Could NOT find KF5Init: found neither KF5InitConfig.cmake nor kf5init-config.cmake 
-- Could NOT find KF5Notifications (missing: KF5Notifications_DIR)
-- Could NOT find KF5Notifications: found neither KF5NotificationsConfig.cmake nor kf5notifications-config.cmake 
-- Could NOT find KF5Package (missing: KF5Package_DIR)
-- Could NOT find KF5Package: found neither KF5PackageConfig.cmake nor kf5package-config.cmake 
-- Could NOT find KF5Plasma (missing: KF5Plasma_DIR)
-- Could NOT find KF5Plasma: found neither KF5PlasmaConfig.cmake nor kf5plasma-config.cmake 
-- Could NOT find KF5Wayland (missing: KF5Wayland_DIR)
-- Could NOT find KF5Wayland: found neither KF5WaylandConfig.cmake nor kf5wayland-config.cmake 
-- Could NOT find KF5WidgetsAddons (missing: KF5WidgetsAddons_DIR)
-- Could NOT find KF5WidgetsAddons: found neither KF5WidgetsAddonsConfig.cmake nor kf5widgetsaddons-config.cmake 
-- Could NOT find KF5WindowSystem (missing: KF5WindowSystem_DIR)
-- Could NOT find KF5WindowSystem: found neither KF5WindowSystemConfig.cmake nor kf5windowsystem-config.cmake 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: Config ConfigWidgets CoreAddons Crash
  GlobalAccel I18n IconThemes IdleTime Init Notifications Package Plasma
  Wayland WidgetsAddons WindowSystem) (Required is at least version "5.62.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:63 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/alex/kwin-5.17.0/CMakeFiles/CMakeOutput.log".

**Comment by KAMiKAZOW** [comment]
Build the entire kwin-lowlatency source code in Launchpad instead of trying to patch it locally. I'm also perfectly happy to accept Kubuntu build support in my OBS repository (linked in ReadMe file).

**Comment by maxiberta** [comment]
I think you're missing the `..` at the end of the `cmake` command line. Manual compilation instructions were very recently updated to add this, see https://github.com/tildearrow/kwin-lowlatency/commit/d634bc01ed691a89c524ec2c907ab25c818cecbd.

**Comment by tildearrow** [comment]
It's been a while. @Alexdegol did you read @maxiberta's comment?

**Comment by tildearrow** [comment]
Closing due to lack of response.
