### ISSUE TITLE
Patch site down

### ISSUE THREAD

**Issue by Vistaus** [tildearrow/kwin-lowlatency#55]
Your website is down, I can't download the patch anymore :(

**Comment by tildearrow** [comment]
Sorry. I will copy some information from [the other bug report](https://github.com/agates/kwin-lowlatency-overlay/issues/18#issuecomment-558444092).

No, sorry. There may not be KWin-lowlatency 5.17.3 after all.
I need to provide a rationale for this.

Two weeks ago, my ISP locked me out again (they did this one year ago but solved the problem quickly) by putting me under a carrier-grade NAT. This basically hinders anyone from accessing the website where the KWin-lowlatency patches are hosted.
agates cannot provide KWin-lowlatency 5.17.3 until the patches become available again.
This is my ISP's fault. Not only they put me under a carrier-grade NAT, but also they took IPv6 away from me! Now that is what you call regressing. Supposedly IPv6 was going to solve the address exhaustion problem.... but nope. They just went the easy way.

I am deeply sorry. I cannot provide patches anymore until I move out (which may happen tomorrow or maybe not).
And I do not have the money for dedicated business-grade Internet access. It costs like $15k-$100k per month, and I... how do you even expect me to afford that?

**Comment by tildearrow** [comment]
I am in the process of evaluating a different internet provider, but looks like I will move out soon again since it is not working either.

In the meanwhile, you can find a patch for 5.17.3 here: [kwin-lowlatency-5.17.3.txt](https://github.com/agates/kwin-lowlatency-overlay/files/3889955/kwin-lowlatency-5.17.3.txt)

**Comment by maxiberta** [comment]
Can't you just upload the patch as a [github release](https://github.com/tildearrow/kwin-lowlatency/releases) asset? Thanks!

**Comment by Vistaus** [comment]
> Can't you just upload the patch as a [github release](https://github.com/tildearrow/kwin-lowlatency/releases) asset? Thanks!

+1

**Comment by robinlahtinen** [comment]
Hetzner VPS is like $3.00 / month

**Comment by tildearrow** [comment]
Won't fix for 5.17.3 - too late.
I am too stressed with my ISP's lies.

**Comment by tildearrow** [comment]
Patch site up! Finally!

(I am going to publish patches through here as well though)
