### ISSUE TITLE
[$2000 open source bounty by TestUFO inventor] All 5 distros should use stutter-free KWin (+variants) by default.

### ISSUE THREAD

**Issue by blurbusters** [tildearrow/kwin-lowlatency#56]
Hello.

# I'm the founder of TestUFO / Blur Busters.  

You know, the motion test website that every power user has been using to gawk at amazement with kwin-lowlatency.  That's me, I'm the creator of TestUFO.

I want to congratulate the developers of kwin-lowlatency for miraculous performance at www.testufo.com/animation-time-graph 

![image](https://user-images.githubusercontent.com/1774867/69767197-276d9800-1149-11ea-88b9-975c72a90e26.png)

This sub-millisecond framepacing even works perfectly on [our experimental 480 Hz monitor](https://www.blurbusters.com/480hz)!  (I bet we're the first to test kwin-lowlatency at 480 Hz...?)

# $2000 Bounty for Reliable TestUFO >60 Hz Under Linux 

Blur Busters is offering a **$2000 open source bounty** to the developer/team that succeeds in getting the top 5 Linux distros to go stutter-free in TestUFO by default.  

# Possible Path: Getting 5 Distros To Use kwin-lowlatency

Theoretically, this might be as simple as convincing 5 major distros to use kwin-lowlatency.  This may be all that qualifies.  If so, then the bounty goes to the kwin-lowlatency team, for example!   Realistically, there's a bit more work, so read on...

# Goal of Bounty: All distros work out of box with stutterfree TestUFO >60Hz

1. User downloads one of the top 5 Linux distributions
2. Users connect a single non-60 Hz monitor.  (whether basic 75 Hz or high-end 144 Hz / 240 Hz)
3. Users launch FireFox or Chrome
4. TestUFO correctly works stutter-free out-of-the-box 

We want to reach the point where we can delete the "VSYNC UNSUPPORTED" message from TestUFO.

# Known Weak Links

- Graphics drivers.  Distributions must have successful Hz-syncing drivers for all top GPUs
- GPUs: Nearly any GPUs in the last 10years pass TestUFO reliably under Windows
- Compositor.  This kwin-lowlatency would be a big winner.  
- Browser.  Both Chrome and FireFox syncs well to kwin-lowlatency, but this needs to be by default.
- Distributions.  Distributions must install all the above preconfigured to stutter free on non-60Hz.
- Politics.  Convincing the distribution makers to configure their distributions for this.

# Conditions:

- Pick any 5 of the pre-qualified distributions: Ubuntu, SuSe, RedHat, Gentoo, Debian, Fedora, Linux Mint (Additional distributions may be qualified by special request; it has to be sufficiently popular)
- Default settings, boilerplate direct download from distribution's website. Only one user action is allowed: Switching from 60Hz to the new refresh rate (refresh rate change), if max refresh rate is not automatically detected.
- Testing will be done by direct download by the Linux distribution website and then installed at default settings 

# How To Test

1. Install distro at default settings
2. Test both FireFox + Chrome + Default browser (only if not FireFox/Chrome)
3. Load www.testufo.com .... Is refresh rate detected correctly?
4. Load www.testufo.com/photo .... Is it running smooth without stutters?
5. Load www.testufo.com/animation-time-graph .... Is it glassfloor to less than 2ms variance?
6. Load www.testufo.com/frameskipping and photograph it.  Is there zero frame skipping?
7. PASS

**NOTE: Ignore the "VSYNC UNSUPPORTED" message.** while manually validating the above.  That boilerplate message (done via useragent detection) for now, will stay hardcoded until the Linux ecosystem is strong enough to permit such an assumption.  Sorry, that's not going to change, *unless there's a reliable way to correctly detect kwin-lowlatency in JavaScript*.  The error message needs to err on side of fail for many legitimate reasons.  There are researchers/students/users/testers loading TestUFO to do scientific display tests and tests of frameskipping during refresh rate overclocking, as well as other browser-based tests that are fully dependent on perfect compositor sync.  (TestUFO even correctly self-detects stutters under Windows in >90% of browser configurations, correctly self-invalidating tests that are researcher/scientist/education/overclocker/tweaker-important!)  **A huge purpose purpose of the bounty is to make that VSYNC UNSUPPORTED message unnecessary.**

During development phase, you may have to fiddle settings or replace kwin, etc, between steps 1 and 2, and then commit those changes and/or do necessary politics (convince the distro maker to make it standard.).

# Bounty Validation Notes

- Requires an auditable trail (i.g. github commits, or emails to distro maker, etc).
- If team, then designate team-leader to receive bounty or mutually-agree on bounty split (or specified mutually-agreed recipient or charity).
- The browser window will be the only window running
-Tested on single monitor system.  Preferred default is for multimonitor system, that the main (primary) monitor is stutter-free.  Windows doesn't do stutterfree discordant-Hz multimonitor either, so we're not making that a requirement.
- May wish to validate more than 5 distributions, so there is an error margin (5 out of 6 working will qualify)
- Will test each distribution a minimum of 10 different random computers pre-qualified to successfully work with Windows 10.   The computers will be randomly selected myself, and be varying ages between early 2010 through today, that supports GPU-acceleration in web browsers.
- Will test AMD, NVIDIA and Intel GPUs made in the last 10 years.  [This requirement may later be reduced to 5 years.  However, high end 10-year GPUs are faster than mid range 5-year GPUs -- example GeForce GTX 480 or 580 still does TestUFO perfectly even to this date]
- Will test only computers reliably capable of 1080p 60fps video under Windows.   That means we will NOT test crappy netbooks.  
- Will test only computers that has successfully achieved stutter-free non-60Hz TestUFO operation under Windows.
- Will test Chrome and FireFox, as well as whatever default browser the distribution uses (if not Chrome or FireFox)
- If computer fails under Windows, that computer will be disqualified from being part of the bounty-testing pool.
- If distro offers multiple preferred desktops, the default-selected (in distribution installer) Window manager must pass. 
- For distros hell-bent on avoiding kwin (and this branch), you may have to modify that compositor too, and get it into the mainline, whereupon the distro maker can compile and include it in their distro. So you might need to fork other non-kwin projects.
- Consolation out: If distro has multiple desktops offered, and the default desktop FAILS -- then at least 2/3rd of other non-default selectable window managers must pass by boilerplate default install (e.g. If 3 desktops are offered, and default fails, the other 2 of 3, even if default fails).
- Consolation out: 1 computer failure out of 10 is permitted.  For every 10 computers that succeeds in correct stutterfree Windows 10 operation, we will permit 9-out-of-10 doing correct stutter-free Linux under default distribution install.
- Bounty is to be paid directly by Blur Busters.  
- We realize we're missing some additional clarity, so feel free to email mark@blurbusters.com to discuss privately.  Or post in the comments thread.

Yes, Windows is not perfect (google "TestUFO stuck at 60 Hz" complaints, often caused by GPU acceleration being disabled for one reason or another), but today is Linux <10% versus Windows >80% in terms of TestUFO refresh rate stutter-free operation on primary monitor (TestUFO as only window).  We will pre-disqualify those Windows systems, and only test systems that already has plug-n-play non-60Hz on Windows 10.  

# Deadline: July 31st, 2020

We realize this is a big ask.  However, this bounty is serious.  We want to signal the distro makers to get the "Hertz shit" together to make non-60Hz as easy in Linux as in Windows.  Lots of you are doing great work, and kwin-lowlatency is a gift from heaven to many users.  But this compositor sync quality needs to be standard, out of the box.

If all distro makers use kwin-lowlatency (and similar works/variants), all the driver vendors (opensource and proprietary) support it with their latest drivers, and on all GPUs, this moves the Linux desktop world much closer to matching the refresh rate reliability of Windows.   

# Potentially Extendable Deadline 

This deadline may be extendable if tangible progress is observed.

# Discussion Welcome

Even if this bounty only generates vigorous debate/discussion, that will still be a success in raising awareness at distro makers.   Since we went retina resolution, the refresh rate race recently started (with the boom of mainstream 120 Hz beginning to happen).   Tomorrow, 240 Hz will eventually be cheap/mainstream like 4K and retina spatial resolution became.   

This bounty is to help encourage along a re-evaluation of sync (software thru photons) in all Linux distros.

**Comment by clapbr** [comment]
Thanks a lot, this is a great idea. A few points :

-  Arch+Manjaro have at the moment one of the largest linux userbases (definetely top5 distros)
- [ Compton fork by yshui](https://github.com/yshui/picom/) (recently renamed to picom) is the compositor people usually go to for performance outside KDE/GNOME ecosystems. Yshui is constantly tweaking for stutter-free.
- GNOME's Mutter recently received a lot of latency/frametime improvements too.
- I suggest BlurBusters should benchmark default compositor behaviors in top5 distros and compare them to non-default kwin-lowlatency and picom. This should raise awareness on users and help maintainers fix their stuff.

**Comment by n4n0GH** [comment]
While $2,000 sounds nice, I feel like the work required for this should be worth more than that.

**Comment by Izaic** [comment]
Kwin is getting it's compositor reworked as we speak by Roman Gilg (sponsored by valve) and a few other contributors. I don't know how big of a change it will be compared to kwin-lowlatency when the patches are finished, but on the other hand it's not likely you'll see any distributions switching over to a fork of kwin.

**Comment by blurbusters** [comment]
To follow up the serious discussion of optimizing the problematic refresh rate architecture of Linux X subsystems --

1. **Consideration: Distros use official git repos rather than forked git repos** 
A great consideration. I was emailed by David at KDE that it is unlikely that kwin-lowlatency is going to be directly adopted by distro makers.  I understand there's a slow long-term code flow upstream (e.g. other repositories surgically adopting useful modifications).  That process may take years to happen.   I understand that too; that's all rolled into the "Politics" category, e.g. distros requiring original repositories to have adopted the modifications.  Whatever path is chosen, I understand that it takes time.  

2. **Consideration: Bounty too small?  Deadline and bounty size is not permanently set in stone.**
The esports gaming industry (Fortnite, etc) is growing 7x from 2019 thru 2029 and with TestUFO breaking excess of one million visits per month, there is super-incredible pressure (on our side) to make browsers plug-play compatible with high-Hz.  That critical mass finally happened with high-Hz Windows and high-Hz Android devices.  

The higher refresh rates are gradually becoming more mainstream (new smartphones, new tablets, etc).  This will be a slowly-increasing pressure over time, since **[retina refresh rates are well beyond 1000 Hz](https://www.blurbusters.com/1000hz-journey)**, confirmed by multiple peer-reviewed scientists now.  A slow gradual long-term refresh rate race has started, and the pressures will only become more-and-more intense.  

This is a progressive increasing-pressure tech feature. As higher-Hz slowly approaching zero-cost cost (much like retina became; and cheap 4K TV costing same as 1080p/720p), this is a new domino-tip that will continue for years and decades until free-cost retina refresh rate is achieved.   With high-Hz becoming more mainstream (smartphones, tablets, esports, etc), the high-Hz industry has boomed.  Blur Busters, being a "Better Than 60 Hz" business (born from a hobby) -- thusly, it is possible that down the road, Blur Busters / TestUFO will obtain the budget to officialize a 5-figure bounty years down the road -- or dedicate hired programmers towards the tasks.  But for now, budget constraints means $2000 is the bounty budget through mid-2020.

I personally (and we, as a business) just want to "encourage the progress along".  Both a hobbyist perspective, and from a business perspective.  Being a high-Hz fan, I have a personal huge hobbyist interest in seeing this happen, and thus, the entire bounty is my founder out-of-pocket donation on behalf of my business.  

**Team-Up for Official BountySource**
If others would like to team-up with me, to enlarge this bounty -- or make it an official BoutySource pot (e.g. several people/organizations donating to create a 5 figure bounty) -- **please contact me at mark [at] blurbusters.com** ... Recently, I did not like hearing about the monthly-inactivity fees that BountySource was planning to do, and other issues.  I rather keep funds in investment account and self-investments where it grows money.  People in the gaming industry trusts Blur Busters ([some credentials here](https://www.blurbusters.com/motion-tests/reviewers-using-pursuit-camera)) -- That said, if multiple 4-figure donors pitch simultaneously too, I'm willing to fall in line and go BountySource or other similar reputable system, while pushing out deadline beyond mid-2020.

**Comment by Izaic** [comment]
> To follow up the serious discussion of optimizing the problematic refresh rate architecture of Linux X subsystems --
> 
>     1. **Consideration: Distros use official git repos rather than forked git repos**
>        A great consideration. I was emailed by David at KDE that it is unlikely that kwin-lowlatency is going to be directly adopted by distro makers.  I understand there's a slow long-term code flow upstream (e.g. other repositories surgically adopting useful modifications).  That process may take years to happen.   I understand that too; that's all rolled into the "Politics" category, e.g. distros requiring original repositories to have adopted the modifications.  Whatever path is chosen, I understand that it takes time.
> 
>     2. **Consideration: Bounty too small?  Deadline and bounty size is not permanently set in stone.**
>        The esports gaming industry (Fortnite, etc) is growing 7x from 2019 thru 2029 and with TestUFO breaking excess of one million visits per month, there is super-incredible pressure (on our side) to make browsers plug-play compatible with high-Hz.  That critical mass finally happened with high-Hz Windows and high-Hz Android devices.
> 
> 
> The higher refresh rates are gradually becoming more mainstream (new smartphones, new tablets, etc). This will be a slowly-increasing pressure over time, since **[retina refresh rates are well beyond 1000 Hz](https://www.blurbusters.com/1000hz-journey)**, confirmed by multiple peer-reviewed scientists now. A slow gradual long-term refresh rate race has started, and the pressures will only become more-and-more intense.
> 
> This is a progressive increasing-pressure tech feature. As higher-Hz slowly approaching zero-cost cost (much like retina became; and cheap 4K TV costing same as 1080p/720p), this is a new domino-tip that will continue for years and decades until free-cost retina refresh rate is achieved. With high-Hz becoming more mainstream (smartphones, tablets, esports, etc), the high-Hz industry has boomed. Blur Busters, being a "Better Than 60 Hz" business (born from a hobby) -- thusly, it is possible that down the road, Blur Busters / TestUFO will obtain the budget to officialize a 5-figure bounty years down the road -- or dedicate hired programmers towards the tasks. But for now, budget constraints means $2000 is the bounty budget through mid-2020.
> 
> I personally (and we, as a business) just want to "encourage the progress along". Both a hobbyist perspective, and from a business perspective. Being a high-Hz fan, I have a personal huge hobbyist interest in seeing this happen, and thus, the entire bounty is my founder out-of-pocket donation on behalf of my business.
> 
> **Team-Up for Official BountySource**
> If others would like to team-up with me, to enlarge this bounty -- or make it an official BoutySource pot (e.g. several people/organizations donating to create a 5 figure bounty) -- **please contact me at mark [at] blurbusters.com** ... Recently, I did not like hearing about the monthly-inactivity fees that BountySource was planning to do, and other issues. I rather keep funds in investment account and self-investments where it grows money. People in the gaming industry trusts Blur Busters ([some credentials here](https://www.blurbusters.com/motion-tests/reviewers-using-pursuit-camera)) -- That said, if multiple 4-figure donors pitch simultaneously too, I'm willing to fall in line and go BountySource or other similar reputable system, while pushing out deadline beyond mid-2020.

https://phabricator.kde.org/T11071 Look into this task list of the work being done on kwin, and then read the rest of my comment.

Considering your "deadline" is somewhere in 2020, and Kwin will probably have most if not all of it's latency improvements by then, why not considering just splitting up and donating that money to the KDE foundation and other linux projects you think may need it? $1000 dollars to the KDE foundation and maybe $1000 to the Linux mint project (another main distro which also happens to maintain it's own desktop and fork of mutter), or Mate...

You can probably write it off on your taxes too, and it's good publicity. As a stop-gap measure for Plasma desktop users, you could do a little banner below the Vsync placeholder that mentions trying alternative compositors such as Kwin-lowlatency if the user isn't having a good experience.

**Comment by blurbusters** [comment]
A compositor overhaul is good news!

That's a damn good suggestion!  That said, the strong desire is for the entire Linux ecosystem rather than just KDE.  Where 9 out of 10 computers that composites stutter-free in browser at correct Hz under Windows, will also do so successfully under Linux.   Including the graphics support, the defaults, all default desktops and window managers, browser.   It's frustrating when there's multiple weak links involved -- I have to see the business case too, in addition to the hobbyist desire.   The question is: How efficiently and quickly can non-60Hz compositing be fixed in a meaningful number of distributions, given things take time, with multiple weak links involved?  There may need to be an advocacy role here.

> you could do a little banner below the Vsync placeholder that mentions trying alternative compositors such as Kwin-lowlatency if the user isn't having a good experience.

That is a good idea!

**Comment by sarthak96** [comment]
> There may need to be an advocacy role here.

This is definitely the case. High refresh rates have been considered a low priority for a long time in linux compositors. To the point where some have even argued the compositor doesn't need to draw at 144fps. This has been the case for input latency as well, since unredirection of fullscreen was removed from kwin with no real replacements

**Comment by megapro17** [comment]
Linux even haven't hardware video acceleration from the box, and you asking for high refresh rates lol. Rip bounty I guess, only two months left

**Comment by joder666** [comment]
GG RIP bounty :( 
Meanwhile i can't even compile it since it breaks if you use the kde unstable repos in opensuse.

**Comment by tildearrow** [comment]
TODO: write apology soon and rationale on rejecting the bounty.

**Comment by megapro17** [comment]
Rip bounty, switching to windows
