### ISSUE TITLE
kwin-lowlatency on xubuntu?

### ISSUE THREAD

**Issue by clusterx** [tildearrow/kwin-lowlatency#58]
can kwin-lowlatency installed on Xubuntu? I just want to use it as window arrangement tool ... what package dependencies are needed without having to install the KDE plasma environment completely?

**Comment by tildearrow** [comment]
Yes, you can, although I have not tried such configuration.
Do `sudo apt-get build-dep kwin-x11` to install the dependencies before building/installing kwin-lowlatency (this will install things like KDE Frameworks and Qt... I'm not sure whether that will require installing the whole Plasma but I don't think so).

**Comment by tildearrow** [comment]
kwin-lowlatency can be installed on Ubuntu and variants using [maxiberta's PPA](https://launchpad.net/~maxiberta/+archive/ubuntu/kwin-lowlatency).
