### ISSUE TITLE
Missing v5.18.1 tag (prevents from building the AUR package)

### ISSUE THREAD

**Issue by DragoonAethis** [tildearrow/kwin-lowlatency#61]
AUR package was updated to use the `v5.18.1` tag, but it was not pushed to the repo, so it fails to build :)

**Comment by tildearrow** [comment]
Upstream v5.18.1 tar is out. Tagged. Fixed.

I just woke up in the morning and released 5.18.1 (since the version number update) but I apparently did it too early since the tar files were not out yet and I needed to update the po...
