### ISSUE TITLE
Higher Cpu usage than before

### ISSUE THREAD

**Issue by StarrKiss** [tildearrow/kwin-lowlatency#66]
Before the 5.18.3 update (on manjaro) kwin with Lowlatency regularly used little to no cpu. Now, it can use up to 7 percent. I have established that happens when mouse is hovering over things running Vulkan. Why this happens, I have no idea.

![Screenshot_20200314_133224](https://user-images.githubusercontent.com/13007697/76688160-6cceac00-65f8-11ea-8edc-0c60adecdc09.png)

**Comment by aufkrawall** [comment]
Try specifically setting the vsync mechanism to "none and hope for the best". Perhaps it resorts to glfinish also for Nvidia in auto mode now, which causes higher CPU load with their driver. Just a wild guess though.

**Comment by tildearrow** [comment]
@StarrKiss Can you report the output of `qdbus org.kde.KWin /KWin supportInformation`, and provide the value of the "VSync mechanism" setting? (under System Settings > Display and Monitor > Compositor)

Oh wait, I see "nvidia" in the screenshot. I think I got to test using my NVIDIA card again :<

**Comment by tildearrow** [comment]
No response D:

I cannot determine the cause without a response :<

Please re-open the issue if you can provide feedback.
