### ISSUE TITLE
Ah, it appears to be April the 1st

### ISSUE THREAD

**Issue by biblicabeebli** [tildearrow/kwin-lowlatency#69]
You know what you did...

**Comment by XakepSDK** [comment]
Nice joke bro

**Comment by StarrKiss** [comment]
Does anyone know what the button does? I enabled it for curiousity and haven't noticed a difference..

**Comment by Kodehawa** [comment]
Oh my godness this is what it was.

**Comment by tildearrow** [comment]
Fixed.
