### ISSUE TITLE
Patch doesn't apply against kwin 5.18.4.1

### ISSUE THREAD

**Issue by realnc** [tildearrow/kwin-lowlatency#71]
https://download.kde.org/stable/plasma/5.18.4/kwin-5.18.4.1.tar.xz

`CMakeLists.txt` fails and seems to contain the patch (or part of it?) already.

**Comment by tildearrow** [comment]
Oh wow, I didn't realize they would make a .1 release...

Please try again with v5.18.4-3 that I just released a bit ago.
If it still fails, please provide reject files.

**Comment by agates** [comment]
This is working against 5.18.4.1 in [the Gentoo overlay](https://github.com/agates/kwin-lowlatency-overlay/issues/29).

**Comment by realnc** [comment]
It still doesn't apply for me. I do:

```
./patch.sh
```

to generate the patch. However, this downloads and creates a patch against `kwin-5.18.4.tar.xz`, not `kwin-5.18.4.1.tar.xz`. Try to apply that fails with:

```
patching file CMakeLists.txt
Reversed (or previously applied) patch detected!  Assume -R? [n]
```

The reject file is:

```diff
$ cat CMakeLists.txt.rej
--- CMakeLists.txt      2020-03-31 14:33:01.000000000 +0300
+++ CMakeLists.txt      2020-04-01 14:35:10.568088719 +0300
@@ -1,7 +1,7 @@
 cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
 
 project(KWIN)
-set(PROJECT_VERSION "5.18.3")
+set(PROJECT_VERSION "5.18.4")
 set(PROJECT_VERSION_MAJOR 5)
 
 set(QT_MIN_VERSION "5.12.0")
```

**Comment by tildearrow** [comment]
*sighs* It appears you downloaded the source tar from releases. I did some changes to the patch maker. Ugh, let me release again...

**Comment by realnc** [comment]
> _sighs_ It appears you downloaded the source tar from releases.

No, I use this git repo.

**Comment by tildearrow** [comment]
Tr-

**Comment by tildearrow** [comment]
I just released 5.18.4-4 with the updated patch maker.

Ugh why KWin team...

**Comment by realnc** [comment]
Yep, works fine now.

**Comment by tildearrow** [comment]
Good to hear.
