### ISSUE TITLE
Add option to use KWIN_USE_INTEL_SWAP_EVENT and patch it

### ISSUE THREAD

**Issue by xalt7x** [tildearrow/kwin-lowlatency#73]
Last year during discussion of Roman Glig's compositing overhaul users [noticed](https://bugs.kde.org/show_bug.cgi?id=344433#c27) that [environment variable KWIN_USE_INTEL_SWAP_EVENT](https://community.kde.org/KWin/Environment_Variables#KWIN_USE_INTEL_SWAP_EVENT) dramatically improved latency. But this option also brings problems when you or some application disable compositor.  Roman fixed it with commit [Reset buffer swap state on stop
](https://phabricator.kde.org/D26090) which was also reverted.
I tried it only with regular KWin but KWin-lowlatency may also benefit from it.

**Comment by tildearrow** [comment]
This could be a good candidate for a VBlank detection method. Thank you for the suggestion.

**Comment by xalt7x** [comment]
@tildearrow 
So I'm still applying patches to kwin-lowlatency for this option

Patch to enable it just as binary tweak..
"[Reset buffer swap state on stop](https://phabricator.kde.org/D26090)" was adjusted to kwin-lowlatency and I'm not sure if it's correct. Could you please review and merge it so users can safely use KWIN_USE_INTEL_SWAP_EVENT environment variable?
Thanks!

Both patches (for 5.18) attached bellow:
[glx_intel_swap_event__for__kwin-lowlatency.tar.gz](https://github.com/tildearrow/kwin-lowlatency/files/4874689/glx_intel_swap_event__for__kwin-lowlatency.tar.gz)

**Comment by An4cl3t0** [comment]
> @tildearrow
> So I'm still applying patches to kwin-lowlatency for this option
> 
> Patch to enable it just as binary tweak..
> "[Reset buffer swap state on stop](https://phabricator.kde.org/D26090)" was adjusted to kwin-lowlatency and I'm not sure if it's correct. Could you please review and merge it so users can safely use KWIN_USE_INTEL_SWAP_EVENT environment variable?
> Thanks!
> 
> Both patches (for 5.18) attached bellow:
> [glx_intel_swap_event__for__kwin-lowlatency.tar.gz](https://github.com/tildearrow/kwin-lowlatency/files/4874689/glx_intel_swap_event__for__kwin-lowlatency.tar.gz)

In standard KWin it freezes for me when I use MPV to play a file with KWIN_USE_INTEL_SWAP_EVENT, is the patch correcting that?

**Comment by tildearrow** [comment]
Closing as 5.22+ implements it (apparently).
