### ISSUE TITLE
LTS branch?

### ISSUE THREAD

**Issue by xalt7x** [tildearrow/kwin-lowlatency#74]
Is there any chance  to have branch for LTS distros (Ubuntu, OpenSUSE Leap). Both of them already have repositories but I'm not sure if maintainers would be able to support them when kwin-lowlatency will move to 5.19.

**Comment by tildearrow** [comment]
KWin-lowlatency 5.18 will be supported even after 5.19 comes out, and updates will be made.

However, I am not so sure if @maxiberta is willing to maintain a package for 5.18 (non-backports).
