### ISSUE TITLE
[RFE] Ubuntu ppa

### ISSUE THREAD

**Issue by zabbal** [tildearrow/kwin-lowlatency#8]
Would be nice to expose this for more people. Having easily installable .deb in Ubuntu ppa might help to bring this to wider audience and improve testing as a result.

**Comment by tildearrow** [comment]
I have considered this in my mind before, but began to doubt because it may require backporting, and setting up a few Ubuntu virtual machines (and I'm running low on disk space).

I will begin working on this as soon as I get an external hard drive to move all my recordings into and hence free some disk space.

**Comment by qwertychouskie** [comment]
If you make a PPA you can use Launchpad's builders, just create a recipe.  E.g.: https://code.launchpad.net/~stk/+recipe/stk-1.0

**Comment by tildearrow** [comment]
Yup, I could, but I need to test that it works as well.

**Comment by zabbal** [comment]
> because it may require backporting

You can always support only the latest kubuntu to minize backporting efforts.

**Comment by KAMiKAZOW** [comment]
> You can always support only the latest kubuntu to minize backporting efforts.

Go for it then. Just take the package definition of KWin on Kubuntu and change a few lines. I did this for openSUSE. Didn't take more than a few minutes.

**Comment by bidinou** [comment]
Hmm, meanwhile (under KDE Neon / Ubuntu based) I made a dirty "make install" over my existing installation (as checkinstall failed to build the deb). I guess that's not advised at all ;-)

Difference with stock kwin is stellar on my 144 Hz display, everything is butter smooth. In 60 Hz I'm not sure, seems slower in some cases (have to double check).

(I just noticed something strange in a game - Two Point Hospital -- where it would scroll without my wanting it until I alt-tabbed -- would happen several times in a session. I'm pretty sure it didn't occur with stock kwin & composition suspension)

**Comment by Izaic** [comment]
> Hmm, meanwhile (under KDE Neon / Ubuntu based) I made a dirty "make install" over my existing installation (as checkinstall failed to build the deb). I guess that's not advised at all ;-)
> 
> Difference with stock kwin is stellar on my 144 Hz display, everything is butter smooth. In 60 Hz I'm not sure, seems slower in some cases (have to double check).
> 
> (I just noticed something strange in a game - Two Point Hospital -- where it would scroll without my wanting it until I alt-tabbed -- would happen several times in a session. I'm pretty sure it didn't occur with stock kwin & composition suspension)

I've noticed that too from time to time, but i thought it was just wine/proton being funny. I'd make a bug report on it if i were you.

**Comment by bidinou** [comment]
> I've noticed that too from time to time, but i thought it was just wine/proton being funny. 
> I'd make a bug report on it if i were you.

Yep, I'm almost sure it doesn't happen with regular kwin (and when disabling compositing it doesn't happen). Thing is I don't know how to have both kwin versions on my single Neon installation. Also, I would maybe have to offer a key of the game to the developer for him to check ;)

Maybe it's time for me to read some KDE devs/triagers wiki...

**Comment by Izaic** [comment]
> > I've noticed that too from time to time, but i thought it was just wine/proton being funny.
> > I'd make a bug report on it if i were you.
> 
> Yep, I'm almost sure it doesn't happen with regular kwin (and when disabling compositing it doesn't happen). Thing is I don't know how to have both kwin versions on my single Neon installation. Also, I would maybe have to offer a key of the game to the developer for him to check ;)
> 
> Maybe it's time for me to read some KDE devs/triagers wiki...

You can run kwin-lowlatency from the build directory without installing it. There are instructions for that in the hacking.md file

**Comment by maxiberta** [comment]
Fyi, I've recently set up a PPA with daily kwin builds based on [this simple Launchpad recipe](https://code.launchpad.net/~maxiberta/+recipe/kwin-lowlatency-kubuntu), which auto-builds packages by merging this repo's code with kubuntu's build instructions:

  https://launchpad.net/~maxiberta/+archive/ubuntu/kwin-lowlatency

Note it's my first PPA and things might break (but it hasn't failed a single build so far, and it did pretty well with the kwin 5.17.2 -> 5.17.3 bump :-) ).

**Comment by tildearrow** [comment]
Marking as done thanks to @maxiberta!
