### ISSUE TITLE
Not building from AUR

### ISSUE THREAD

**Issue by janlimpens** [tildearrow/kwin-lowlatency#87]
CMake Error at CMakeLists.txt:128 (find_package):
  Could not find a package configuration file provided by "KWaylandServer"
  with any of the following names:

    KWaylandServerConfig.cmake
    kwaylandserver-config.cmake

  Add the installation prefix of "KWaylandServer" to CMAKE_PREFIX_PATH or set
  "KWaylandServer_DIR" to a directory containing one of the above files.  If
  "KWaylandServer" provides a separate development package or SDK, be sure it
  has been installed.
CMake Error.log shows this:

/usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -DCHECK_FUNCTION_EXISTS=pthread_create  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now  -rdynamic CMakeFiles/cmTC_10c88.dir/CheckFunctionExists.c.o  -o cmTC_10c88  -lpthreads 
/usr/bin/ld: não foi possível localizar -lpthreads
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[1]: *** [CMakeFiles/cmTC_10c88.dir/build.make:107: cmTC_10c88] Fehler 1
make[1]: Verzeichnis „/home/xxx/.cache/yay/kwin-lowlatency/src/build/CMakeFiles/CMakeTmp“ wird verlassen
make: *** [Makefile:141: cmTC_10c88/fast] Fehler 2

(sorry for the localized mixup)

**Comment by Berobad** [comment]
It's part of the kwayland-server package, 5.19 now needs kwayland installed

**Comment by veganvelociraptor** [comment]
Installing kwayland-server and kwayland made some progress, but not all the way thru:

> [ 82%] Building CXX object CMakeFiles/kwin.dir/tabbox/tabbox.cpp.o
/home/xx/.cache/yay/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp: In lambda function:
/home/xx/.cache/yay/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp:536:44: error: 'class ScreenLocker::KSldApp' has no member named 'setWaylandFd'
  536 |             ScreenLocker::KSldApp::self()->setWaylandFd(clientFd);
      |                                            ^~~~~~~~~~~~
/home/xx/.cache/yay/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp:540:66: error: 'userActivity' is not a member of 'ScreenLocker::KSldApp'
  540 |                         screenLockerApp, &ScreenLocker::KSldApp::userActivity);
      |                                                                  ^~~~~~~~~~~~
/home/xx/.cache/yay/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp: In lambda function:
/home/xx/.cache/yay/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp:555:69: error: 'userActivity' is not a member of 'ScreenLocker::KSldApp'
  555 |                            screenLockerApp, &ScreenLocker::KSldApp::userActivity);
      |                                                                     ^~~~~~~~~~~~
/home/xx/.cache/yay/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp:557:44: error: 'class ScreenLocker::KSldApp' has no member named 'setWaylandFd'
  557 |             ScreenLocker::KSldApp::self()->setWaylandFd(-1);
      |                                            ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/kwin.dir/build.make:1552: CMakeFiles/kwin.dir/wayland_server.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2311: CMakeFiles/kwin.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: kwin-lowlatency'

CMakeError.log says:

> /home/xx/.cache/yay/kwin-lowlatency/src/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:2:10: fatal error: sys/procctl.h: No such file or directory

**Comment by tildearrow** [comment]
Fixing AUR package to include kwayland-server. Please install Plasma 5.19 first (vanilla KWin included) and then try building again.

**Comment by tildearrow** [comment]
5.19.0-2 out. Please test.

**Comment by veganvelociraptor** [comment]
Working now. Thanks @tildearrow!
