### ISSUE TITLE
It stops compilating at 81% every single time

### ISSUE THREAD

**Issue by snakedye** [tildearrow/kwin-lowlatency#88]
`
[ 79%] Building CXX object CMakeFiles/kwin.dir/touch_hide_cursor_spy.cpp.o
[ 79%] Building CXX object CMakeFiles/kwin.dir/tablet_input.cpp.o
[ 79%] Building CXX object CMakeFiles/kwin.dir/touch_input.cpp.o
[ 79%] Building CXX object CMakeFiles/kwin.dir/udev.cpp.o
[ 80%] Building CXX object CMakeFiles/kwin.dir/unmanaged.cpp.o
[ 80%] Building CXX object CMakeFiles/kwin.dir/useractions.cpp.o
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/tablet_input.cpp: 
In member function ‘void 
KWin::TabletInputRedirection::tabletToolEvent(KWin::InputRedirection::
TabletEventType, const QPointF&, qreal, int, int, qreal, bool, bool, quint64, 
quint64, KWin::InputRedirection::TabletToolType, const 
QVector<KWin::InputRedirection::Capability>&, quint32, 
KWin::LibInput::Device*)’:
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/tablet_input.cpp:
93:112: warning: ‘t’ may be used uninitialized in this function 
[-Wmaybe-uninitialized]
   93 |                     Qt::NoModifier, toolId, button, button, toolType, 
capabilities, serialId, device->sysName());
      |                                                                          
                                      ^
[ 80%] Building CXX object CMakeFiles/kwin.dir/utils.cpp.o
[ 80%] Building CXX object CMakeFiles/kwin.dir/virtualdesktops.cpp.o
[ 80%] Building CXX object CMakeFiles/kwin.dir/virtualdesktopsdbustypes.cpp.o
[ 80%] Building CXX object CMakeFiles/kwin.dir/virtualkeyboard.cpp.o
[ 80%] Building CXX object CMakeFiles/kwin.dir/virtualkeyboard_dbus.cpp.o
[ 80%] Building CXX object 
CMakeFiles/kwin.dir/was_user_interaction_x11_filter.cpp.o
[ 80%] Building CXX object CMakeFiles/kwin.dir/wayland_cursor_theme.cpp.o
[ 81%] Building CXX object CMakeFiles/kwin.dir/wayland_server.cpp.o
[ 81%] Building CXX object 
CMakeFiles/kwin.dir/window_property_notify_x11_filter.cpp.o
[ 81%] Building CXX object CMakeFiles/kwin.dir/workspace.cpp.o
[ 81%] Building CXX object CMakeFiles/kwin.dir/x11client.cpp.o
[ 81%] Building CXX object CMakeFiles/kwin.dir/x11eventfilter.cpp.o
[ 81%] Building CXX object CMakeFiles/kwin.dir/xcbutils.cpp.o
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.
cpp: In lambda function:
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.
cpp:536:44: error: ‘class ScreenLocker::KSldApp’ has no member named 
‘setWaylandFd’
  536 |             ScreenLocker::KSldApp::self()->setWaylandFd(clientFd);
      |                                            ^~~~~~~~~~~~
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.
cpp:540:66: error: ‘userActivity’ is not a member of ‘ScreenLocker::KSldApp’
  540 |                         screenLockerApp, 
&ScreenLocker::KSldApp::userActivity);
      |                                                                  
^~~~~~~~~~~~
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.
cpp: In lambda function:
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.
cpp:555:69: error: ‘userActivity’ is not a member of ‘ScreenLocker::KSldApp’
  555 |                            screenLockerApp, 
&ScreenLocker::KSldApp::userActivity);
      |                                                                     
^~~~~~~~~~~~
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.
cpp:557:44: error: ‘class ScreenLocker::KSldApp’ has no member named 
‘setWaylandFd’
  557 |             ScreenLocker::KSldApp::self()->setWaylandFd(-1);
      |                                            ^~~~~~~~~~~~
[ 81%] Building CXX object CMakeFiles/kwin.dir/xdgshellclient.cpp.o
make[2]: *** [CMakeFiles/kwin.dir/build.make:1552: 
CMakeFiles/kwin.dir/wayland_server.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/x11client.cpp: In 
member function ‘virtual void KWin::X11Client::changeMaximize(bool, bool, 
bool)’:
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/x11client.cpp:
4389:52: warning: ‘T* QWeakPointer<T>::data() const [with T = 
KDecoration2::DecoratedClient]’ is deprecated: Use toStrongRef() instead, and 
data() on the returned QSharedPointer [-Wdeprecated-declarations]
 4389 |         const auto c = decoration()->client().data();
      |                                                    ^
In file included from /usr/include/qt/QtCore/qsharedpointer.h:48,
                 from /usr/include/qt/QtCore/QSharedPointer:1,
                 from /usr/include/KF5/KConfigCore/kconfigwatcher.h:11,
                 from /usr/include/KF5/KConfigCore/KConfigWatcher:1,
                 from 
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/options.h:29,
                 from 
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/x11client.h:25,
                 from 
/var/tmp/pamac-build-bryan/kwin-lowlatency/src/kwin-lowlatency/x11client.cpp:22:
/usr/include/qt/QtCore/qsharedpointer_impl.h:565:8: note: declared here
  565 |     T *data() const noexcept { return internalData(); }
      |        ^~~~
make[1]: *** [CMakeFiles/Makefile2:2311: CMakeFiles/kwin.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...`

**Comment by tildearrow** [comment]
Please update your packages to Plasma 5.19 first.
This error is well-known and caused by outdated packages.

**Comment by tildearrow** [comment]
Added warnings to README.md
