### ISSUE TITLE
Patch for 5.15.5 does not compile

### ISSUE THREAD

**Issue by ValdikSS** [tildearrow/kwin-lowlatency#9]
The patch from the website for kwin 5.15.5 does not compile due to:
```
kwin/u/rpmbuild/BUILD/kwin-5.15.5/scripting/scriptedeffect.cpp:156:15: error: 'options' was not declared in this scope
  156 |       switch (options->animationCurve()) {
      |               ^~~~~~~
```

**Comment by ZaWertun** [comment]
Can't see any problems applying the patch.

FYI: It's already built for Fedora 29/30 - https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/907435/.

**Comment by tildearrow** [comment]
Are you building the test suite too? Before a specific commit the test suite wasn't able to be built. Try again with `-DBUILD_TESTING=OFF`.

(I'll update the patches soon, however)

**Comment by ValdikSS** [comment]
I've just added patch to Fedora's kwin.spec, without changing anything else.
Now I use a build from COPR, it works.

**Comment by tildearrow** [comment]
A build from COPR? May you provide a link to it?

**Comment by ValdikSS** [comment]
It's already linked by @ZaWertun 
https://copr.fedorainfracloud.org/coprs/zawertun/kde/build/907435/

**Comment by tildearrow** [comment]
Oh! Sorry, I didn't notice. @ZaWertun Is it possible for me to add your link to README?

(by the way, I just updated the patch)

**Comment by ZaWertun** [comment]
Sure, you can add it.
