### ISSUE TITLE
Manjaro installation is unclear for new users

### ISSUE THREAD

**Issue by ghost** [tildearrow/kwin-lowlatency#91]
I feel this needs to be said for everyone who isn't a super Linux expert and is just trying to get this thing installed. It makes sense to me that the actual instructions should be visible in full literate description for new users.

The current instructions for Manjaro:
```
git clone https://aur.archlinux.org/kwin-lowlatency.git
cd kwin-lowlatency
git checkout 16cccd1703d4f6ea8831ee2cc424f218acec95d3
```

All this does is invoke some sort of weird 'git checkout' thing. It assumes the user knows what they are looking at or knows what to do after this point. It does not actually install anything whatsoever. Based on having instructions to change directory "cd" into the proper installation directory, it would seem natural that hand-holding steps beyond this would be of the same context.

I literally only just learned after ~6 months as a Linux user that this 'git checkout 16cccd1703d4f6ea8831ee2cc424f218acec95d3' function lets the user work with the branch of code you are intending for the user to see, in this case being the 5.18 branch designed for Manjaro. If this were not invoked, one would be using the 5.19 branch which you have clearly stated does not work with Manjaro yet.

The full instructions should be:
```
git clone https://aur.archlinux.org/kwin-lowlatency.git
cd kwin-lowlatency
git checkout 16cccd1703d4f6ea8831ee2cc424f218acec95d3
makepkg
(May need extra-cmake-modules installed. Run sudo pacman -S extra-cmake-modules if so)
sudo pacman -U kwin-lowlatency-5.18.5-3-x86_64.pkg.tar.xz

This will replace kwin with kwin-lowlatency and it will be immediately available for use.
```

My apologies for seeming rude, but good, explicit instructions are often very scarce, I find. Too much is assumed that the user is experienced and knows everything with only the bare threads of information given.

**Comment by tildearrow** [comment]
I have updated the readme and added a new kwin-lowlatency-manjaro repository in order to remove the cryptic checkout line.

Please tell me whether this is clear now.

**Comment by ghost** [comment]
Thank you, the new instructions are perfectly clear and I believe that users of any level should be able to execute them just fine. There is no cryptic nature now. I just performed a fresh install of Manjaro KDE Plasma 20.0.3 in order to give proper feedback on this:

Performing the exact installation instructions from the new repository copy-paste installs kwin-lowlatency flawlessly and I especially like that you condensed my take on the installation to:

`$ makepkg -sri`

which temporarily installs all the cmake dependencies then removes them when done. How nice and thoughtful!

As a side note, I know in the past installing kwin-lowlatency from the AUR repository using pamac errors out and it still appears to produce the same failure:

```
make[1]: *** [CMakeFiles/Makefile2:2311: CMakeFiles/kwin.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by tildearrow** [comment]
No problem. I am sorry for any issue, but usability problems should not be there in any way. Thank you for pointing it out.

Honestly I was kind of stressed with the Manjaro setWaylandDisplay overload, and the fact they never catch up with the latest Plasma in time, despite calling themselves "rolling-release".

This is why I just spammed "READ BELOW FOR MANJARO" throughout the README. I was just not in a good mood because too many issues with my life and ugh... what can I say? I have to take the pain for sure. I deserve it all!

About the side note, this is because Manjaro only has Plasma 5.18 and the package in the AUR tracks 5.19.
5.19 breaks something around the setWayland* thingy, making it not work under 5.18.
