### ISSUE TITLE
Manjaro - compilation error

### ISSUE THREAD

**Issue by PeterBadzhakov** [tildearrow/kwin-lowlatency#92]
Both default AUR PKGBUILD and using the one provided in the README.md of this repo lead to an error in compilation.

System:
**Manjaro 20.0.3 Lysia, x86_64 Linux 5.7.0-3-MANJARO, KDE 5.70.0**

Error excerpt:
```
[ 82%] Building CXX object CMakeFiles/kwin.dir/wayland_cursor_theme.cpp.o
[ 82%] Building CXX object CMakeFiles/kwin.dir/wayland_server.cpp.o
[ 82%] Building CXX object CMakeFiles/kwin.dir/window_property_notify_x11_filter.cpp.o
[ 82%] Building CXX object CMakeFiles/kwin.dir/workspace.cpp.o
[ 82%] Building CXX object CMakeFiles/kwin.dir/x11client.cpp.o
[ 82%] Building CXX object CMakeFiles/kwin.dir/x11eventfilter.cpp.o
[ 83%] Building CXX object CMakeFiles/kwin.dir/xcbutils.cpp.o
[ 83%] Building CXX object CMakeFiles/kwin.dir/xdgshellclient.cpp.o
/var/tmp/pamac-build-dan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp: In member function ‘void KWin::WaylandServer::initScreenLocker()’:
/var/tmp/pamac-build-dan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp:512:36: error: ‘class ScreenLocker::KSldApp’ has no member named ‘setWaylandDisplay’
  512 |     ScreenLocker::KSldApp::self()->setWaylandDisplay(m_display);
      |                                    ^~~~~~~~~~~~~~~~~
/var/tmp/pamac-build-dan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp:516:68: error: ‘greeterClientConnectionChanged’ is not a member of ‘ScreenLocker::KSldApp’
  516 |     connect(ScreenLocker::KSldApp::self(), &ScreenLocker::KSldApp::greeterClientConnectionChanged, this,
      |                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/pamac-build-dan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp: In lambda function:
/var/tmp/pamac-build-dan/kwin-lowlatency/src/kwin-lowlatency/wayland_server.cpp:518:77: error: ‘class ScreenLocker::KSldApp’ has no member named ‘greeterClientConnection’
  518 |             m_screenLockerClientConnection = ScreenLocker::KSldApp::self()->greeterClientConnection();
      |                                                                             ^~~~~~~~~~~~~~~~~~~~~~~
```

Full error message:
[pastebin, time-limit 1mo](https://pastebin.com/a6RMYALd)

**Comment by tildearrow** [comment]
> KDE 5.70.0

That is the version of Frameworks.
What about the version of Plasma? I am sure it is 5.18.

You may want to follow the in- wait... So this also happens with the 5.18 PKGBUILD?

**Comment by PeterBadzhakov** [comment]
Sorry for the lack of information. Checking currently installed packages:

**plasma-desktop**: 5.18.5-2
**plasma-workspace**: 5.18.5-3
**plasma-framework-git**: 5.71.0
**Qt dependencies** are all version 5.15

After the original PKGBUILD failed, I cleared my AUR cache and substituted them with your files from the README.md repo. Build failed on the same spot for the same reason.

**Comment by tildearrow** [comment]
Hmm... Is there any reason why are you using plasma-framework-git instead of the normal plasma-framework?

**Comment by PeterBadzhakov** [comment]
It failed with the default one so I figured I need newer code. I usually prefer to compile from source but it's never been a problem.

**Comment by tildearrow** [comment]
> It failed with the default one so I figured I need newer code. I usually prefer to compile from source but it's never been a problem.

Hmmm... Can you try again with the non-git Plasma framework and the 5.18 PKGBUILD?

**Comment by PeterBadzhakov** [comment]
Installed default plasma framework and cleared cache. With your PKGBUILD:

[Build failed pastebin](https://pastebin.com/jJhZUEAA)
[diff of build files, am I doing something wrong?](https://pastebin.com/HBtXyYTm)

**Comment by tildearrow** [comment]
Hmmm.... nope. You seem to be doing everything correctly.

What is the version of kscreenlocker?

**Comment by PeterBadzhakov** [comment]
**kscreenlocker**: 5.18.5-1

I reinstalled it and build kwin-lowlatency **successfully**! I don't know what covertly changed.

**Comment by PeterBadzhakov** [comment]
Confirming kwin-lowlatency works flawlessly. Thank you very much for the assisstance. Great code.
