### ISSUE TITLE
Tumbleweed: libkwin.so.5 undefined symbol

### ISSUE THREAD

**Issue by berny156** [tildearrow/kwin-lowlatency#93]
kwin-lowlatency-5.18.5-2.4.x86_64.rpm installs cleanly on latest Tumbleweed. Starting `kwin_x11` results in the error message:

libkwin.so.5: undefined symbol: _ZN12ScreenLocker7KSldApp30greeterClientConnectionChangedEv

**Comment by berny156** [comment]
Just found another repo with latest version which is running great!

**Comment by tildearrow** [comment]
The screen locker again...

Please build kwin-lowlatency 5.19 manually for now. The next version of KF5 breaks the screen locker API.

@KAMiKAZOW may you provide an answer?...

**Comment by tildearrow** [comment]
But wait, what is that "another repo"? I am curious.

**Comment by KAMiKAZOW** [comment]
@tildearrow Sadly, I cannot use Linux at the moment because my last two PCs broke down and the replacement (Surface Pro 7) needs a custom kernel which I was not yet able to package for openSUSE.

**Comment by tildearrow** [comment]
It is fine. I have found it anyway, and am contacting the author of the repo.
