### ISSUE TITLE
Endless "no vsync" lines with AMDGPU

### ISSUE THREAD

**Issue by frumble** [tildearrow/kwin-lowlatency#96]
I do not assume that this is the expected result:

$ kwin_x11 --replace
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 180, resource id: 98566151, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 181, resource id: 98566151, major code: 20 (GetProperty), minor code: 0
OpenGL vendor string:                   X.Org
OpenGL renderer string:                 AMD Radeon RX 5700 XT 50th Anniversary (NAVI10, DRM 3.38.0, 5.8.10-arch1-1, LLVM 10.0.1)
OpenGL version string:                  4.6 (Core Profile) Mesa 20.1.8
OpenGL shading language version string: 4.60
Driver:                                 RadeonSI
GPU class:                              Navi
OpenGL version:                         4.6
GLSL version:                           4.60
Mesa version:                           20.1.8
X server version:                       1.20.9
Linux kernel version:                   5.8.10
Requires strict binding:                no
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
no vsync
no vsync
…

No AMDGPU-Pro installed. Installed kwin-lowlatency 5.19.5-1 via AUR on Arch.

**Comment by tildearrow** [comment]
Oh! This is debug code that I forgot to remove...

Do you have VSync off?

**Comment by tildearrow** [comment]
Assuming yes. Closing issue as fixed.

**Comment by soredake** [comment]
Could you please release 5.18.6 with this commit?

**Comment by tildearrow** [comment]
@soredake Done. Thanks for pointing out.

**Comment by frumble** [comment]
Indeed, it’s gone now, good.
