### ISSUE TITLE
Ugh. Pressing Alt-Tab may crash KWin, oh come on.

### ISSUE THREAD

**Issue by tildearrow** [tildearrow/kwin-lowlatency#97]
Apparently even pressing alt-tab crashes KWin. Amazing.

How to reproduce:
1. Turn on your computer
2. Wait, wait and wait
3. Work for a bit
4. Get off and exercise for one hour
5. Take a shower
6. Come back and play for a bit
7. Press Alt-Tab
8. Repeat 7 until it crashes

**Comment by rnd-ash** [comment]
Is this on an NVIDIA GPU ?

Also please say which version of kwin your using

**Comment by deathtrip** [comment]
Alt-tabbing works fine for me on AMD gpu, using the radeon driver.

**Comment by bvobart** [comment]
I'm having a similar problem. Sometimes such an Alt-Tab crash happens on a fresh boot after having used my laptop for several hours, but more often it happens after suspend (not necessarily immediately after waking from suspend, can take a while too). KWin and / or latte-dock also crash sometimes when I hover my mouse over my latte-dock icons to show their window previews (thumbnails). I notice that the animation to smoothly raise and inflate the icons in latte-dock upon hovering over them works fine, but exactly at the point that the window preview is supposed to show up, either KWin or latte-dock crashes (or both).

So I have a feeling this problem may relate to rendering the window previews somehow (maybe specifically those of windows that have been open for a long time and had their window preview garbage collected in the mean time?), though I don't know how this truly works under the hood.

I'm running Manjaro KDE on an Asus Zephyrus M GM501GS (has an Nvidia GTX1070) with kernel 5.8.18-1-MANJARO, kwin-lowlatency version 5.20.3, and Nvidia driver version 455.45.01 (from `mhwd`'s `video-hybrid-intel-nvidia-455xx-prime` preset). All settings in System Settings -> Display and Monitor -> Compositor are still on their defaults, afaik.

What can I do to debug this issue further? Are there any logs or something that I can collect and share?

**Comment by jsebean** [comment]
> Is this on an NVIDIA GPU ?
> 
> Also please say which version of kwin your using

Yea I cannot say I've ever experienced this issue on AMDGPU (RX 580).

**Comment by tildearrow** [comment]
Probably related to the previous issue on Present Windows effect. Haven't reproduced in a few months. Closing...
