### ISSUE TITLE
Latest update to Ubuntu PPA for Focal causes kwin-lowlatency to commit suicide

### ISSUE THREAD

**Issue by KerfuffleV2** [tildearrow/kwin-lowlatency#98]
Focal doesn't have KDE 5.18.6 nor does the kubuntu-backports PPA for it - it's still on 5.18.5. The required dependencies actually cause the update process to uninstall kwin entirely leaving the system non-functional. It's not even possible to revert to the previous version of kwin-lowlatency which supports 5.18.5 once taking that step since it seems to have been removed entirely from the PPA.

Example of what happens when attempting to upgrade packages after the latest kwin-lowlatency update on the PPA:

```
# apt dist-upgrade

The following packages were automatically installed and are no longer required:
  kwin-wayland-backend-drm xwayland
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  kubuntu-desktop kwin kwin-addons kwin-wayland kwin-x11 latte-dock plasma-workspace-wayland
The following packages have been kept back:
  kwin-data libkwin4-effect-builtins1 libkwineffects12
The following packages will be upgraded:
  kwin-wayland-backend-drm kwin-wayland-backend-x11 libkwinglutils12 libkwinxrenderutils12
4 upgraded, 0 newly installed, 7 to remove and 3 not upgraded.
```

Update has no changes to perform with the kwin-lowlatency PPA removed:

```
# apt dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

System is a pretty normal focal install, as far as I know:
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

I don't create many issues on github so I apologize in advance if I left out any information or creating this was out of line.

**Comment by maxiberta** [comment]
Ouch! Apologies. PPA author here. Updated to Ubuntu 20.10b recently so I didn't notice such a mess in 20.04 :-/ . I'm reverting the PPA to kwin 5.8.15 now.
Thanks!

**Comment by KerfuffleV2** [comment]
@maxiberta Thanks for the reply and your work maintaining the PPA! Unfortunately, the latest change still doesn't work correctly on Focal:
```
# apt dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  kubuntu-desktop kwin-addons kwin-x11 latte-dock
The following packages have been kept back:
  kwin-data libkwin4-effect-builtins1 libkwineffects12
The following packages will be upgraded:
  libkwinglutils12 libkwinxrenderutils12
2 upgraded, 0 newly installed, 4 to remove and 3 not upgraded.
```
When trying to force the kwin-lowlatency versions:
```
# apt install kwin-x11=4:5.18.5-0ubuntu0.1+lowlatency15471+kubuntu497+202010031519~ubuntu20.04.1 kwin-common=4:5.18.5-0ubuntu0.1+lowlatency15471+kubuntu497+202010031519~ubuntu20.04.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kwin-common : Depends: libkf5windowsystem5 (>= 5.69.0) but 5.68.0-0ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

It seems to depend on a version of libkf5windowsystem5 that doesn't exist in Focal. I'm not sure if there are other package dependencies other than that which will fail after fixing the libkf5windosystem5 part. 

If there's anything you want me to give you information about for packages/libraries on my system, please let me know!

**Comment by maxiberta** [comment]
Yup, just noticed that :-) ... Dropping [ppa:kubuntu-ppa/backports-landing](https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/backports-landing) from the PPA's build deps should fix it. [Rebuilding now](https://code.launchpad.net/~maxiberta/+recipe/kwin-lowlatency-kubuntu-focal)!

Thanks again!

**Comment by KerfuffleV2** [comment]
@maxiberta I can confirm it now upgrades and runs on my system. Thanks a lot!

It's probably not important but kwin still thinks it is 5.18.6: 
```
$ kwin --version
kwin 5.18.6
```
I think previously it also indicated it was low-latency when displaying the version. It definitely is the correct version now and the compositor settings show the stuff that's not in vanilla kwin.

From my perspective, this is resolved, so I'll let you close the issue whenever you think is appropriate. Please let me know if any further testing would be helpful from me.

**Comment by maxiberta** [comment]
Yay! Let me attempt one last rebuild with bumped `debian/changelog` so that the .deb version is 5.18.6.

**Comment by tildearrow** [comment]
Doing `kwin_x11 --version` should not indicate it is the low-latency fork in any way.

**Comment by KerfuffleV2** [comment]
It's possible I misremembered, but I even see `kwin --version` in my history from when I originally installed kwin-lowlatency and I could swear it said something about being lowlatency.

@maxiberta I updated to that last build and everything still looks good. Thanks once more!

**Comment by KerfuffleV2** [comment]
Do you want me to close the issue? I was going to let you do it but not sure of the etiquette. From my perspective, the problem is solved.
